const fs = require('fs');
const path = require('path');

const ROOT_DIR = path.resolve(__dirname, '..');
const OPT_DIR = path.join(ROOT_DIR, 'poster', 'opt');

// Full curated metadata for all 131 poster files
const posterCatalog = [
  // ==========================================
  // 🎬 MOVIES (Cinema, Marvel, DC, Pop Culture, Directors, Tamil)
  // ==========================================
  {
    file: '1513605.png',
    title: 'MILES MORALES | Sunset Skyline',
    subtitle: 'Marvel Cinema · Archival Print',
    category: 'Movies',
    collection: 'Marvel & Cinema',
    artist: 'PINBOARD Marvel Studio',
    subject: 'Miles Morales atop Brooklyn skyscraper at sunset',
    badge: 'HOT',
    regularPrice: 849,
    salePrice: 649,
    rating: 4.9,
    reviewCount: 480,
    tags: ['movies', 'marvel', 'spiderman', 'spider-man', 'miles morales', 'into the spiderverse', 'brooklyn', 'superhero', 'comic', 'animation'],
    keywords: 'miles morales spider-man spiderman marvel superhero into the spider-verse brooklyn sunset skyline cinema movie comic'
  },
  {
    file: '1513609.png',
    title: 'BREAKING BAD | Desert Lawn Chairs',
    subtitle: 'Cult Television · Archival Print',
    category: 'Movies',
    collection: 'Cult Cinema',
    artist: 'Studio PINBOARD',
    subject: 'Walter White and Jesse Pinkman in desert lawn chairs',
    badge: 'TRENDING',
    regularPrice: 899,
    salePrice: 699,
    rating: 4.9,
    reviewCount: 520,
    tags: ['movies', 'breaking bad', 'walter white', 'jesse pinkman', 'heisenberg', 'amc', 'cult', 'hollywood', 'drama'],
    keywords: 'breaking bad walter white heisenberg jesse pinkman desert lawn chairs rv meth crime drama amc television movie'
  },
  {
    file: '1513618.png',
    title: 'THE AMAZING SPIDER-MAN | Peter & Gwen',
    subtitle: 'Marvel Cinema · Romance Print',
    category: 'Movies',
    collection: 'Marvel & Cinema',
    artist: 'PINBOARD Marvel Studio',
    subject: 'Peter Parker and Gwen Stacy rooftop embrace NYC',
    badge: null,
    regularPrice: 849,
    salePrice: 649,
    rating: 4.8,
    reviewCount: 310,
    tags: ['movies', 'marvel', 'spiderman', 'spider-man', 'peter parker', 'gwen stacy', 'andrew garfield', 'superhero', 'hollywood', 'romance'],
    keywords: 'the amazing spider-man peter parker gwen stacy andrew garfield emma stone marvel superhero romance nyc rooftop'
  },
  {
    file: '1513633.png',
    title: 'BROOKLYN BABY | Lana Del Rey',
    subtitle: 'Cinematic Music · Monochromatic Print',
    category: 'Movies',
    collection: 'Cult Cinema',
    artist: 'Vintage Vinyl Studio',
    subject: 'Lana Del Rey in convertible car Brooklyn Baby lyrics',
    badge: 'AESTHETIC',
    regularPrice: 799,
    salePrice: 599,
    rating: 4.9,
    reviewCount: 410,
    tags: ['movies', 'hollywood', 'lana del rey', 'brooklyn baby', 'music', 'cinematic', 'vintage', 'monochrome', 'pop culture'],
    keywords: 'lana del rey brooklyn baby ultraviolence cinematic vintage retro monochrome indie music pop culture vinyl'
  },
  {
    file: '1513635.png',
    title: 'SPIDER-MAN | Daily Bugle & Headphones',
    subtitle: 'Marvel Cinema · Urban Editorial Print',
    category: 'Movies',
    collection: 'Marvel & Cinema',
    artist: 'PINBOARD Marvel Studio',
    subject: 'Spider-Man relaxing on fire escape reading Daily Bugle',
    badge: 'POPULAR',
    regularPrice: 849,
    salePrice: 649,
    rating: 4.8,
    reviewCount: 290,
    tags: ['movies', 'marvel', 'spiderman', 'spider-man', 'peter parker', 'daily bugle', 'headphones', 'superhero', 'comic', 'action'],
    keywords: 'spider-man spiderman headphones daily bugle newspaper peter parker marvel superhero nyc urban chill comic'
  },
  {
    file: '1513638.png',
    title: 'MEMORIES OF MURDER | Bong Joon-ho',
    subtitle: 'World Cinema · Auteur Print',
    category: 'Movies',
    collection: 'Cult Cinema',
    artist: 'Cinephile Archives',
    subject: 'Song Kang-ho in the golden reed fields Memories of Murder',
    badge: null,
    regularPrice: 899,
    salePrice: 699,
    rating: 4.9,
    reviewCount: 380,
    tags: ['movies', 'memories of murder', 'bong joon ho', 'song kang ho', 'korean cinema', 'thriller', 'hollywood', 'auteur', 'crime'],
    keywords: 'memories of murder bong joon-ho song kang-ho korean cinema auteur crime thriller reed field golden hour film'
  },
  {
    file: '1513639.png',
    title: 'PARASITE | Oscar Winner 2020',
    subtitle: 'World Cinema · Palme d\'Or Print',
    category: 'Movies',
    collection: 'Cult Cinema',
    artist: 'Cinephile Archives',
    subject: 'Parasite lawn garden party eye-bar censor minimalist art',
    badge: 'BESTSELLER',
    regularPrice: 899,
    salePrice: 699,
    rating: 5.0,
    reviewCount: 710,
    tags: ['movies', 'parasite', 'bong joon ho', 'oscar', 'palme dor', 'korean cinema', 'hollywood', 'thriller', 'black comedy'],
    keywords: 'parasite bong joon-ho academy award best picture palme dor korean movie park family kim family modern classic'
  },
  {
    file: '1513641.png',
    title: 'PRISONERS | Denis Villeneuve',
    subtitle: 'Modern Noir · Fine Art Print',
    category: 'Movies',
    collection: 'Cult Cinema',
    artist: 'Cinephile Archives',
    subject: 'Hugh Jackman and Jake Gyllenhaal foggy rain Prisoners',
    badge: null,
    regularPrice: 849,
    salePrice: 649,
    rating: 4.8,
    reviewCount: 260,
    tags: ['movies', 'prisoners', 'denis villeneuve', 'hugh jackman', 'jake gyllenhaal', 'roger deakins', 'thriller', 'hollywood'],
    keywords: 'prisoners denis villeneuve hugh jackman jake gyllenhaal roger deakins mystery crime thriller maze cinematic'
  },
  {
    file: '1513642.png',
    title: 'MEN ARE BRAVE | The Dark Knight Emblem',
    subtitle: 'DC Universe · Heavy Shadow Print',
    category: 'Movies',
    collection: 'DC & Gotham',
    artist: 'DC Cinematic Studio',
    subject: 'Batman Dark Knight silhouette with Men Are Brave typography',
    badge: 'POPULAR',
    regularPrice: 849,
    salePrice: 649,
    rating: 4.9,
    reviewCount: 440,
    tags: ['movies', 'dc', 'batman', 'the dark knight', 'bruce wayne', 'gotham', 'superhero', 'action', 'men are brave'],
    keywords: 'batman dc comics the dark knight bruce wayne gotham city men are brave superhero silhouette vigilante'
  },
  {
    file: '1513644.png',
    title: 'PETER & MJ | Mirror Selfie',
    subtitle: 'Marvel Cinema · Candid Polaroids',
    category: 'Movies',
    collection: 'Marvel & Cinema',
    artist: 'PINBOARD Marvel Studio',
    subject: 'Peter Parker and MJ taking casual mirror photo in costume',
    badge: null,
    regularPrice: 799,
    salePrice: 599,
    rating: 4.8,
    reviewCount: 340,
    tags: ['movies', 'marvel', 'spiderman', 'spider-man', 'peter parker', 'mj', 'zendaya', 'tom holland', 'romance', 'superhero'],
    keywords: 'spider-man peter parker mj michelle jones zendaya tom holland mirror selfie candid marvel superhero romance'
  },
  {
    file: '1514058.png',
    title: 'THE TRUMAN SHOW | Stairway to the Sky',
    subtitle: 'Cult Cinema · Surrealist Print',
    category: 'Movies',
    collection: 'Cult Cinema',
    artist: 'Studio PINBOARD',
    subject: 'Jim Carrey bowing at the edge of the sky dome exit door',
    badge: 'STAFF PICK',
    regularPrice: 899,
    salePrice: 699,
    rating: 4.9,
    reviewCount: 610,
    tags: ['movies', 'the truman show', 'jim carrey', 'peter weir', 'in case i dont see ya', 'hollywood', 'philosophical', 'sci-fi'],
    keywords: 'the truman show jim carrey peter weir good afternoon good evening and good night stairs exit sky dome existential'
  },
  {
    file: '1514060.png',
    title: 'FIGHT CLUB | Split Identity Silhouette',
    subtitle: 'Cult Cinema · Dual Mind Minimalist',
    category: 'Movies',
    collection: 'Cult Cinema',
    artist: 'Studio PINBOARD',
    subject: 'Narrator and Tyler Durden split silhouette Fight Club',
    badge: 'POPULAR',
    regularPrice: 849,
    salePrice: 649,
    rating: 4.9,
    reviewCount: 590,
    tags: ['movies', 'fight club', 'tyler durden', 'brad pitt', 'edward norton', 'david fincher', 'cult', 'hollywood', 'action'],
    keywords: 'fight club tyler durden brad pitt edward norton david fincher project mayhem first rule split identity soap'
  },
  {
    file: '1514061.png',
    title: 'JOHN WICK | Neon Rain Silhouette',
    subtitle: 'Action Cinema · Violet Neon Print',
    category: 'Movies',
    collection: 'Cult Cinema',
    artist: 'Neo Tokyo & Cinema',
    subject: 'Keanu Reeves John Wick silhouette in violet rain glow',
    badge: 'HOT',
    regularPrice: 849,
    salePrice: 649,
    rating: 4.9,
    reviewCount: 460,
    tags: ['movies', 'john wick', 'keanu reeves', 'baba yaga', 'continental', 'action', 'hollywood', 'neon', 'assassin'],
    keywords: 'john wick keanu reeves baba yaga gun fu assassin continental hotel neon violet rain action thriller'
  },
  {
    file: '1514078.png',
    title: 'JOHN WICK & MUSTANG | Baba Yaga',
    subtitle: 'Action Cinema · Mustang & Dog Print',
    category: 'Movies',
    collection: 'Cult Cinema',
    artist: 'Studio PINBOARD',
    subject: 'John Wick leaning on 1969 Boss 429 Mustang with Pitbull',
    badge: null,
    regularPrice: 849,
    salePrice: 649,
    rating: 4.8,
    reviewCount: 380,
    tags: ['movies', 'john wick', 'keanu reeves', 'baba yaga', 'mustang', '1969 boss 429', 'action', 'hollywood', 'dog'],
    keywords: 'john wick 1969 ford mustang boss 429 pitbull keanu reeves baba yaga action movie muscle car assassin'
  },
  {
    file: '1514079.png',
    title: 'LANA DEL REY | Stage Spotlight',
    subtitle: 'Cinematic Music · Monochromatic Print',
    category: 'Movies',
    collection: 'Cult Cinema',
    artist: 'Vintage Vinyl Studio',
    subject: 'Lana Del Rey in dramatic stage spotlight black and white',
    badge: null,
    regularPrice: 799,
    salePrice: 599,
    rating: 4.8,
    reviewCount: 290,
    tags: ['movies', 'hollywood', 'lana del rey', 'music', 'cinematic', 'monochrome', 'black and white', 'spotlight', 'pop culture'],
    keywords: 'lana del rey concert live stage spotlight monochrome black and white vintage americana retro cinema pop'
  },
  {
    file: '1514083.png',
    title: 'THE SHINING | Jack Torrance',
    subtitle: 'Psychological Horror · Stanley Kubrick',
    category: 'Movies',
    collection: 'Cult Cinema',
    artist: 'Overlook Press',
    subject: 'Jack Nicholson as Jack Torrance axe door peek The Shining',
    badge: 'STAFF PICK',
    regularPrice: 899,
    salePrice: 699,
    rating: 4.9,
    reviewCount: 670,
    tags: ['movies', 'the shining', 'stanley kubrick', 'jack nicholson', 'jack torrance', 'heres johnny', 'overlook hotel', 'horror', 'hollywood'],
    keywords: 'the shining stanley kubrick jack nicholson jack torrance heres johnny overlook hotel horror classic cult cinema'
  },
  {
    file: '1514117.png',
    title: 'TYLER DURDEN | Soap & Smoke Magazine',
    subtitle: 'Cult Cinema · Grunge Editorial Print',
    category: 'Movies',
    collection: 'Cult Cinema',
    artist: 'Studio PINBOARD',
    subject: 'Tyler Durden pink sunglasses smoking cigarette Fight Club issue',
    badge: 'TRENDING',
    regularPrice: 849,
    salePrice: 649,
    rating: 4.9,
    reviewCount: 510,
    tags: ['movies', 'fight club', 'tyler durden', 'brad pitt', 'soap', 'magazine', 'cult', 'hollywood', 'action'],
    keywords: 'fight club tyler durden brad pitt pink sunglasses cigarette smoke editorial vintage magazine retro grunge'
  },
  {
    file: '1514119.png',
    title: 'IRON MAN | Tony Stark Legacy',
    subtitle: 'Marvel Cinema · Retrospective Print',
    category: 'Movies',
    collection: 'Marvel & Cinema',
    artist: 'PINBOARD Marvel Studio',
    subject: 'Robert Downey Jr. Tony Stark arc reactor blueprint collage',
    badge: 'POPULAR',
    regularPrice: 899,
    salePrice: 699,
    rating: 5.0,
    reviewCount: 880,
    tags: ['movies', 'marvel', 'iron man', 'tony stark', 'robert downey jr', 'avengers', 'arc reactor', 'superhero', 'action', 'sci-fi'],
    keywords: 'iron man tony stark robert downey jr rdj i am iron man avengers arc reactor marvel cinematic universe mcu'
  },
  {
    file: '1514131.png',
    title: 'INTERSTELLAR | Cooper & Gargantua',
    subtitle: 'Sci-Fi Cinema · Christopher Nolan',
    category: 'Movies',
    collection: 'Cult Cinema',
    artist: 'Endurance Archives',
    subject: 'Cooper astronaut helmet reflecting black hole Gargantua',
    badge: 'HOT',
    regularPrice: 899,
    salePrice: 699,
    rating: 5.0,
    reviewCount: 940,
    tags: ['movies', 'interstellar', 'christopher nolan', 'cooper', 'matthew mcconaughey', 'gargantua', 'sci-fi', 'space', 'hollywood'],
    keywords: 'interstellar christopher nolan matthew mcconaughey cooper gargantua black hole space exploration time dilation sci-fi'
  },
  {
    file: '1514132.png',
    title: 'FIGHT CLUB | The Trio Monochrome',
    subtitle: 'Cult Cinema · Noir Character Study',
    category: 'Movies',
    collection: 'Cult Cinema',
    artist: 'Studio PINBOARD',
    subject: 'Tyler Durden, Marla Singer, and the Narrator in monochrome',
    badge: null,
    regularPrice: 849,
    salePrice: 649,
    rating: 4.8,
    reviewCount: 310,
    tags: ['movies', 'fight club', 'tyler durden', 'marla singer', 'brad pitt', 'helena bonham carter', 'edward norton', 'cult', 'hollywood'],
    keywords: 'fight club marla singer tyler durden narrator brad pitt helena bonham carter edward norton monochrome noir'
  },
  {
    file: '1514133.png',
    title: 'FIGHT CLUB | Neon Chemical Green',
    subtitle: 'Cult Cinema · Chemical Burn Edition',
    category: 'Movies',
    collection: 'Cult Cinema',
    artist: 'Studio PINBOARD',
    subject: 'Chemical burn scene and soap formula in glowing toxic green',
    badge: null,
    regularPrice: 849,
    salePrice: 649,
    rating: 4.7,
    reviewCount: 220,
    tags: ['movies', 'fight club', 'chemical burn', 'neon green', 'tyler durden', 'brad pitt', 'cult', 'hollywood', 'action'],
    keywords: 'fight club chemical burn lye kiss neon green tyler durden brad pitt acid test anarchism cult cinema'
  },
  {
    file: '1514134.png',
    title: 'AMERICAN PSYCHO | Patrick Bateman Red Suit',
    subtitle: 'Cult Cinema · Monochromatic Crimson',
    category: 'Movies',
    collection: 'Cult Cinema',
    artist: 'Studio PINBOARD',
    subject: 'Christian Bale as Patrick Bateman with headphones in crimson',
    badge: 'TRENDING',
    regularPrice: 849,
    salePrice: 649,
    rating: 4.9,
    reviewCount: 560,
    tags: ['movies', 'american psycho', 'patrick bateman', 'christian bale', 'huey lewis', 'business card', 'cult', 'hollywood'],
    keywords: 'american psycho patrick bateman christian bale wall street yuppie business card axe raincoat cult cinema'
  },
  {
    file: '1514163.png',
    title: 'AFTER HOURS | The Weeknd Red Suit',
    subtitle: 'Cinematic Music · Neon Boulevard Print',
    category: 'Movies',
    collection: 'Cult Cinema',
    artist: 'XO Visuals',
    subject: 'Abel Tesfaye in crimson jacket sunglasses against neon dark',
    badge: 'HOT',
    regularPrice: 799,
    salePrice: 599,
    rating: 4.9,
    reviewCount: 420,
    tags: ['movies', 'the weeknd', 'after hours', 'abel tesfaye', 'blinding lights', 'music', 'cinematic', 'hollywood', 'pop culture'],
    keywords: 'the weeknd after hours abel tesfaye red suit blinding lights neon las vegas synthwave cinematic music'
  },
  {
    file: '1514165.png',
    title: 'FIGHT CLUB | Pink Soap Rules',
    subtitle: 'Cult Cinema · Pop Art Soap Edition',
    category: 'Movies',
    collection: 'Cult Cinema',
    artist: 'Studio PINBOARD',
    subject: 'Iconic pink Fight Club soap bar with rules typography',
    badge: 'POPULAR',
    regularPrice: 849,
    salePrice: 649,
    rating: 4.9,
    reviewCount: 480,
    tags: ['movies', 'fight club', 'soap', 'tyler durden', 'rules of fight club', 'pop art', 'cult', 'hollywood', 'action'],
    keywords: 'fight club pink soap rules of fight club tyler durden brad pitt pop art graphic design cult movie'
  },
  {
    file: '1514168.png',
    title: 'THE WEEKND | After Hours Tracklist',
    subtitle: 'Cinematic Music · Archival Vinyl Print',
    category: 'Movies',
    collection: 'Cult Cinema',
    artist: 'XO Visuals',
    subject: 'After Hours typography cassette tracklist and noir portraits',
    badge: null,
    regularPrice: 799,
    salePrice: 599,
    rating: 4.8,
    reviewCount: 290,
    tags: ['movies', 'the weeknd', 'after hours', 'tracklist', 'music', 'cinematic', 'vinyl', 'hollywood', 'pop culture'],
    keywords: 'the weeknd after hours tracklist vinyl typography noir cassette abel tesfaye music album poster'
  },
  {
    file: '1514169.png',
    title: 'LANA DEL REY | Ultraviolence Vintage Press',
    subtitle: 'Cinematic Music · Newspaper Collage',
    category: 'Movies',
    collection: 'Cult Cinema',
    artist: 'Vintage Vinyl Studio',
    subject: 'Lana Del Rey vintage newspaper collage with lyrics and cigarette',
    badge: null,
    regularPrice: 799,
    salePrice: 599,
    rating: 4.9,
    reviewCount: 370,
    tags: ['movies', 'hollywood', 'lana del rey', 'ultraviolence', 'newspaper', 'collage', 'music', 'cinematic', 'vintage'],
    keywords: 'lana del rey ultraviolence newspaper collage vintage indie music typography retro monochrome poster'
  },
  {
    file: '1514179.png',
    title: 'PETER PARKER | No Way Home NYC',
    subtitle: 'Marvel Cinema · Emotional Horizon',
    category: 'Movies',
    collection: 'Marvel & Cinema',
    artist: 'PINBOARD Marvel Studio',
    subject: 'Tom Holland Peter Parker atop snowy NYC rooftop looking into dusk',
    badge: null,
    regularPrice: 849,
    salePrice: 649,
    rating: 4.8,
    reviewCount: 390,
    tags: ['movies', 'marvel', 'spiderman', 'spider-man', 'peter parker', 'no way home', 'tom holland', 'superhero', 'action', 'sci-fi'],
    keywords: 'spider-man no way home peter parker tom holland marvel superhero snow nyc dusk rooftop cinema'
  },
  {
    file: '1514230.png',
    title: 'END OF BEGINNING | Djo Joe Keery',
    subtitle: 'Cinematic Music · Indie Wave Print',
    category: 'Movies',
    collection: 'Cult Cinema',
    artist: 'Indie Soundwaves',
    subject: 'Joe Keery retro spectacles Chicago lyrics End of Beginning',
    badge: 'TRENDING',
    regularPrice: 799,
    salePrice: 599,
    rating: 4.8,
    reviewCount: 320,
    tags: ['movies', 'stranger things', 'joe keery', 'djo', 'end of beginning', 'chicago', 'music', 'hollywood', 'indie'],
    keywords: 'djo joe keery steve harrington stranger things end of beginning chicago lyrics polaroid indie music poster'
  },
  {
    file: '1514231.png',
    title: 'INTO THE SPIDER-VERSE | Leap of Faith',
    subtitle: 'Marvel Cinema · Iconic Freefall Print',
    category: 'Movies',
    collection: 'Marvel & Cinema',
    artist: 'PINBOARD Marvel Studio',
    subject: 'Miles Morales inverted dive against towering Manhattan skyline',
    badge: 'BESTSELLER',
    regularPrice: 899,
    salePrice: 699,
    rating: 5.0,
    reviewCount: 1100,
    tags: ['movies', 'marvel', 'spiderman', 'spider-man', 'miles morales', 'leap of faith', 'into the spider-verse', 'animation', 'superhero'],
    keywords: 'into the spider-verse miles morales leap of faith freefall whats up danger inverted dive marvel animation'
  },
  {
    file: '1514312.png',
    title: 'SPIDER-MAN | The Suit Reveal',
    subtitle: 'Marvel Cinema · Close-Up Fabric Texture',
    category: 'Movies',
    collection: 'Marvel & Cinema',
    artist: 'PINBOARD Marvel Studio',
    subject: 'High-detail macro shot of Spider-Man classic red and blue fabric',
    badge: null,
    regularPrice: 849,
    salePrice: 649,
    rating: 4.8,
    reviewCount: 280,
    tags: ['movies', 'marvel', 'spiderman', 'spider-man', 'peter parker', 'suit', 'macro', 'superhero', 'comic'],
    keywords: 'spider-man suit reveal macro texture fabric red blue webbing peter parker marvel superhero detail'
  },
  {
    file: '1514313.png',
    title: 'SPIDER-MAN | Crimson Emblem Weave',
    subtitle: 'Marvel Cinema · Minimalist Spider Crest',
    category: 'Movies',
    collection: 'Marvel & Cinema',
    artist: 'PINBOARD Marvel Studio',
    subject: 'Black spider emblem embossed on vivid crimson honeycomb mesh',
    badge: null,
    regularPrice: 849,
    salePrice: 649,
    rating: 4.8,
    reviewCount: 250,
    tags: ['movies', 'marvel', 'spiderman', 'spider-man', 'spider emblem', 'crimson', 'minimalist', 'superhero', 'comic'],
    keywords: 'spider-man emblem spider crest crimson honeycomb mesh minimalist marvel superhero wallpaper print'
  },
  {
    file: '1553160.jpg',
    title: 'I AM DOOM | Monarch of Latveria',
    subtitle: 'Marvel Cinema · Sovereign Emerald Print',
    category: 'Movies',
    collection: 'Marvel & Cinema',
    artist: 'Latverian State Archive',
    subject: 'Doctor Victor von Doom sitting on iron throne in emerald cloak',
    badge: 'HOT',
    regularPrice: 899,
    salePrice: 699,
    rating: 4.9,
    reviewCount: 540,
    tags: ['movies', 'marvel', 'doctor doom', 'victor von doom', 'fantastic four', 'latveria', 'supervillain', 'comic', 'action'],
    keywords: 'doctor doom victor von doom i am doom monarch latveria emerald green cloak iron mask fantastic four marvel'
  },
  {
    file: '1553164.jpg',
    title: 'ANSWERS TO HELLME | Doctor Doom Statue',
    subtitle: 'Marvel Comics · Sovereign Stone Edition',
    category: 'Movies',
    collection: 'Marvel & Cinema',
    artist: 'Latverian State Archive',
    subject: 'Stone monument of Doctor Doom towering over Latverian plaza',
    badge: null,
    regularPrice: 849,
    salePrice: 649,
    rating: 4.8,
    reviewCount: 310,
    tags: ['movies', 'marvel', 'doctor doom', 'victor von doom', 'monument', 'comic', 'latveria', 'supervillain'],
    keywords: 'doctor doom victor von doom answers to hellme latveria monument stone statue marvel villain comic art'
  },
  {
    file: '1553256_1.jpg',
    title: 'REBIRTH | Tom Holland Spider-Man',
    subtitle: 'Marvel Cinema · Integrated Suit Print',
    category: 'Movies',
    collection: 'Marvel & Cinema',
    artist: 'PINBOARD Marvel Studio',
    subject: 'Spider-Man standing victorious atop rain-slicked Queens rooftop',
    badge: 'POPULAR',
    regularPrice: 849,
    salePrice: 649,
    rating: 4.9,
    reviewCount: 460,
    tags: ['movies', 'marvel', 'spiderman', 'spider-man', 'tom holland', 'rebirth', 'queens', 'superhero', 'action'],
    keywords: 'spider-man rebirth tom holland integrated suit queens nyc rain slicked rooftop marvel cinematic universe'
  },
  {
    file: '1553985.png',
    title: 'ATONEMENT | Dunkirk Beach Horizon',
    subtitle: 'Romantic Cinema · Joe Wright Masterpiece',
    category: 'Movies',
    collection: 'Cult Cinema',
    artist: 'Studio PINBOARD',
    subject: 'Robbie Turner walking along the dreamlike Dunkirk shore',
    badge: null,
    regularPrice: 849,
    salePrice: 649,
    rating: 4.9,
    reviewCount: 390,
    tags: ['movies', 'atonement', 'joe wright', 'james mcavoy', 'keira knightley', 'dunkirk', 'hollywood', 'romance', 'war'],
    keywords: 'atonement joe wright james mcavoy keira knightley robbie turner dunkirk beach horizon period drama romance'
  },
  {
    file: '1554029.png',
    title: 'SPIDER-MAN | Crimson Noir Silhouette',
    subtitle: 'Marvel Cinema · Shadow & Scarlet Edition',
    category: 'Movies',
    collection: 'Marvel & Cinema',
    artist: 'PINBOARD Marvel Studio',
    subject: 'Spider-Man crouching in deep shadow with neon scarlet outline',
    badge: null,
    regularPrice: 849,
    salePrice: 649,
    rating: 4.8,
    reviewCount: 270,
    tags: ['movies', 'marvel', 'spiderman', 'spider-man', 'noir', 'crimson', 'silhouette', 'superhero', 'action'],
    keywords: 'spider-man crimson dark silhouette shadow red outline crouching superhero marvel comic poster'
  },
  {
    file: '1554461.png',
    title: 'LA CASA DE PAPEL | Money Heist Resistance',
    subtitle: 'Television Cinema · Bella Ciao Print',
    category: 'Movies',
    collection: 'Cult Cinema',
    artist: 'Studio PINBOARD',
    subject: 'El Profesor, Salvador Dali masks, and the Royal Mint heist crew',
    badge: 'POPULAR',
    regularPrice: 849,
    salePrice: 649,
    rating: 4.9,
    reviewCount: 580,
    tags: ['movies', 'money heist', 'la casa de papel', 'el profesor', 'dali mask', 'bella ciao', 'tokyo', 'berlin', 'action'],
    keywords: 'money heist la casa de papel el profesor salvador dali mask red jumpsuit royal mint netflix series bella ciao'
  },
  {
    file: '1554475.png',
    title: 'ANBE SIVAM | Kamal Haasan Tribute',
    subtitle: 'Tamil Cinema Classics · Expressionist Oil',
    category: 'Movies',
    collection: 'Tamil Cinema Legends',
    artist: 'Kollywood Fine Arts',
    subject: 'Kamal Haasan as Nalla Sivam with scar and warm radiant smile',
    badge: 'LEGEND',
    regularPrice: 899,
    salePrice: 699,
    rating: 5.0,
    reviewCount: 920,
    tags: ['movies', 'tamil', 'kamal haasan', 'anbe sivam', 'nalla sivam', 'kollywood', 'classic', 'cinema', 'philosophy'],
    keywords: 'anbe sivam kamal haasan nalla sivam love is god madhavan sundar c kollywood tamil cinema masterpiece'
  },
  {
    file: '1554486.png',
    title: 'THE AMAZING SPIDER-MAN | NYC Street View',
    subtitle: 'Marvel Cinema · Street Photography Print',
    category: 'Movies',
    collection: 'Marvel & Cinema',
    artist: 'PINBOARD Marvel Studio',
    subject: 'Spider-Man swinging through yellow cabs and Manhattan traffic',
    badge: null,
    regularPrice: 849,
    salePrice: 649,
    rating: 4.8,
    reviewCount: 310,
    tags: ['movies', 'marvel', 'spiderman', 'spider-man', 'andrew garfield', 'manhattan', 'nyc', 'superhero', 'action'],
    keywords: 'the amazing spider-man andrew garfield manhattan yellow cab traffic swinging new york city marvel superhero'
  },
  {
    file: '1554487.png',
    title: 'STRANGER THINGS | The Mind Flayer Skies',
    subtitle: 'Cult Television · 80s Retro Synthwave',
    category: 'Movies',
    collection: 'Cult Cinema',
    artist: 'Hawkins AV Club',
    subject: 'The kids on bicycles facing the towering red shadow Mind Flayer',
    badge: 'HOT',
    regularPrice: 849,
    salePrice: 649,
    rating: 4.9,
    reviewCount: 640,
    tags: ['movies', 'stranger things', 'eleven', 'mind flayer', 'upside down', 'hawkins', 'retro', '80s', 'sci-fi'],
    keywords: 'stranger things eleven mike will dustin lucas mind flayer upside down hawkins indiana netflix 80s synthwave'
  },
  {
    file: '1554548.jpg',
    title: 'WANNA COOK? | Walter & Saul',
    subtitle: 'Cult Cinema · Albuquerque Crime Duo',
    category: 'Movies',
    collection: 'Cult Cinema',
    artist: 'Studio PINBOARD',
    subject: 'Walter White Heisenberg and Saul Goodman in yellow hazmat suits',
    badge: 'POPULAR',
    regularPrice: 849,
    salePrice: 649,
    rating: 4.9,
    reviewCount: 470,
    tags: ['movies', 'breaking bad', 'better call saul', 'walter white', 'saul goodman', 'heisenberg', 'amc', 'hollywood'],
    keywords: 'wanna cook walter white saul goodman bob odenkirk bryan cranston breaking bad better call saul yellow hazmat'
  },
  {
    file: '1555620.png',
    title: 'CHANDRA | Saree & Red Rose',
    subtitle: 'Tamil Cinema Classics · Romantic Nostalgia',
    category: 'Movies',
    collection: 'Tamil Cinema Legends',
    artist: 'Kollywood Fine Arts',
    subject: 'Chandra in traditional silk saree holding deep crimson rose',
    badge: 'AESTHETIC',
    regularPrice: 799,
    salePrice: 599,
    rating: 4.8,
    reviewCount: 310,
    tags: ['movies', 'tamil', 'chandra', 'devadas', 'kollywood', 'vintage', 'saree', 'romance', 'classic'],
    keywords: 'chandra devadas tamil cinema vintage saree red rose traditional beauty classic kollywood romance'
  },
  {
    file: '1555662.png',
    title: 'DEVADAS | Smoke & Midnight Shadow',
    subtitle: 'Tamil Cinema Classics · Tragic Hero Silhouette',
    category: 'Movies',
    collection: 'Tamil Cinema Legends',
    artist: 'Kollywood Fine Arts',
    subject: 'Devadas sitting in shadow with wisps of white smoke and liquor bottle',
    badge: null,
    regularPrice: 799,
    salePrice: 599,
    rating: 4.8,
    reviewCount: 260,
    tags: ['movies', 'tamil', 'devadas', 'kollywood', 'smoke', 'silhouette', 'vintage', 'classic', 'drama'],
    keywords: 'devadas tamil cinema kollywood tragic romance smoke silhouette darkness vintage drama classic'
  },
  {
    file: '1555887.png',
    title: 'DEXTER & JANE | Red Curtains & Shadows',
    subtitle: 'Cult Television · Blood Spatter Room',
    category: 'Movies',
    collection: 'Cult Cinema',
    artist: 'Studio PINBOARD',
    subject: 'Dexter Morgan in vinyl kill room with deep red velvet curtains',
    badge: null,
    regularPrice: 849,
    salePrice: 649,
    rating: 4.8,
    reviewCount: 290,
    tags: ['movies', 'dexter', 'dexter morgan', 'michael c hall', 'blood spatter', 'kill room', 'cult', 'hollywood', 'thriller'],
    keywords: 'dexter morgan michael c hall miami metro police blood spatter kill room red curtains showtime thriller'
  },
  {
    file: '1555892.png',
    title: 'THE BATMAN | Crimson Silhouette',
    subtitle: 'DC Universe · Matt Reeves Noir Print',
    category: 'Movies',
    collection: 'DC & Gotham',
    artist: 'DC Cinematic Studio',
    subject: 'Robert Pattinson Batman emerging through crimson smoke and rain',
    badge: 'HOT',
    regularPrice: 899,
    salePrice: 699,
    rating: 5.0,
    reviewCount: 780,
    tags: ['movies', 'dc', 'the batman', 'batman', 'robert pattinson', 'matt reeves', 'gotham', 'superhero', 'action'],
    keywords: 'the batman robert pattinson matt reeves vengeance gotham city red crimson rain silhouette dc comics'
  },
  {
    file: '1555893.png',
    title: 'SUPERMAN | Cape in the Wind Over Earth',
    subtitle: 'DC Universe · Cosmic Hope Edition',
    category: 'Movies',
    collection: 'DC & Gotham',
    artist: 'DC Cinematic Studio',
    subject: 'Superman floating above the curvature of Earth as crimson cape billows',
    badge: 'POPULAR',
    regularPrice: 899,
    salePrice: 699,
    rating: 4.9,
    reviewCount: 620,
    tags: ['movies', 'dc', 'superman', 'clark kent', 'man of steel', 'krypton', 'earth', 'superhero', 'sci-fi'],
    keywords: 'superman clark kent man of steel henry cavill david corenswet earth orbit crimson cape dc comics hope'
  },
  {
    file: '1555894.png',
    title: 'THE BATMAN | Gotham Rooftop Glider',
    subtitle: 'DC Universe · Wingsuit Over Gotham',
    category: 'Movies',
    collection: 'DC & Gotham',
    artist: 'DC Cinematic Studio',
    subject: 'Batman stepping off Gotham clocktower ledge into wingsuit flight',
    badge: null,
    regularPrice: 849,
    salePrice: 649,
    rating: 4.8,
    reviewCount: 390,
    tags: ['movies', 'dc', 'batman', 'the batman', 'gotham', 'wingsuit', 'rooftop', 'superhero', 'action'],
    keywords: 'batman gotham city rooftop wingsuit glider flight night vigilante dc comics superhero architecture'
  },
  {
    file: '1555899.png',
    title: 'MASTER JD | The Last Supper Halo',
    subtitle: 'Tamil Cinema Legends · Thalapathy Vijay Print',
    category: 'Movies',
    collection: 'Tamil Cinema Legends',
    artist: 'Kollywood Fine Arts',
    subject: 'Thalapathy Vijay as Professor JD with sunglasses and cat at banquet',
    badge: 'BESTSELLER',
    regularPrice: 949,
    salePrice: 749,
    rating: 5.0,
    reviewCount: 1250,
    tags: ['movies', 'tamil', 'vijay', 'thalapathy vijay', 'master', 'lokesh kanagaraj', 'kollywood', 'cinema', 'action'],
    keywords: 'master jd thalapathy vijay lokesh kanagaraj last supper cat sunglasses professor JD kollywood tamil cinema'
  },
  {
    file: '1555934.png',
    title: 'LANA DEL REY | Halftone Pop Art',
    subtitle: 'Cinematic Music · Halftone Dot Graphic',
    category: 'Movies',
    collection: 'Cult Cinema',
    artist: 'Vintage Vinyl Studio',
    subject: 'Lana Del Rey lighting cigarette with bold repeat typography',
    badge: null,
    regularPrice: 799,
    salePrice: 599,
    rating: 4.8,
    reviewCount: 260,
    tags: ['movies', 'hollywood', 'lana del rey', 'pop art', 'halftone', 'retro', 'music', 'cinematic', 'vintage'],
    keywords: 'lana del rey halftone dot screenprint pop art typography cigarette lighter vintage americana poster'
  },
  {
    file: '1555937.png',
    title: 'WE LIVE IN TIME | Florence & Andrew',
    subtitle: 'Romantic Cinema · Contemporary A2 Print',
    category: 'Movies',
    collection: 'Cult Cinema',
    artist: 'Studio PINBOARD',
    subject: 'Andrew Garfield and Florence Pugh in quiet intimate embrace',
    badge: 'NEW DROP',
    regularPrice: 849,
    salePrice: 649,
    rating: 4.9,
    reviewCount: 330,
    tags: ['movies', 'we live in time', 'andrew garfield', 'florence pugh', 'a24', 'romance', 'hollywood', 'drama'],
    keywords: 'we live in time andrew garfield florence pugh romance contemporary drama love story cinema poster'
  },
  {
    file: '1555939.png',
    title: 'LEO & VIKRAM | LCU Double Exposure',
    subtitle: 'Tamil Cinema Legends · Lokesh Cinematic Universe',
    category: 'Movies',
    collection: 'Tamil Cinema Legends',
    artist: 'Kollywood Fine Arts',
    subject: 'Thalapathy Vijay Leo and Kamal Haasan Vikram dual exposure',
    badge: 'HOT',
    regularPrice: 949,
    salePrice: 749,
    rating: 5.0,
    reviewCount: 1420,
    tags: ['movies', 'tamil', 'leo', 'vikram', 'lcu', 'lokesh kanagaraj', 'thalapathy vijay', 'kamal haasan', 'kollywood', 'action'],
    keywords: 'leo vikram lcu lokesh cinematic universe thalapathy vijay kamal haasan bloody sweet kollywood tamil cinema'
  },
  {
    file: '1555940.png',
    title: 'A LOVE OF LIGHT & SHADOWS | Master',
    subtitle: 'Tamil Cinema Legends · Vijay & Malavika',
    category: 'Movies',
    collection: 'Tamil Cinema Legends',
    artist: 'Kollywood Fine Arts',
    subject: 'Vijay and Malavika Mohanan sitting on illuminated metro steps',
    badge: null,
    regularPrice: 849,
    salePrice: 649,
    rating: 4.8,
    reviewCount: 370,
    tags: ['movies', 'tamil', 'master', 'thalapathy vijay', 'malavika mohanan', 'kollywood', 'romance', 'cinema'],
    keywords: 'master thalapathy vijay malavika mohanan love of light and shadows steps golden light kollywood romance'
  },
  {
    file: '1555941.png',
    title: 'SUPERMAN | Solar Ascension',
    subtitle: 'DC Universe · Dawn of Justice Sunrise',
    category: 'Movies',
    collection: 'DC & Gotham',
    artist: 'DC Cinematic Studio',
    subject: 'Superman rising into golden sunlight absorbing yellow sun energy',
    badge: 'POPULAR',
    regularPrice: 849,
    salePrice: 649,
    rating: 4.9,
    reviewCount: 490,
    tags: ['movies', 'dc', 'superman', 'clark kent', 'man of steel', 'solar', 'sunrise', 'superhero', 'sci-fi'],
    keywords: 'superman solar ascension sun energy golden dawn clark kent man of steel dc comics superhero'
  },
  {
    file: '1555943.png',
    title: 'BEFORE IT ALL ENDED | Walter & Jesse RV',
    subtitle: 'Cult Cinema · Crystal Ship Nostalgia',
    category: 'Movies',
    collection: 'Cult Cinema',
    artist: 'Studio PINBOARD',
    subject: 'Walter White and Jesse Pinkman resting on desert dirt road beside RV',
    badge: null,
    regularPrice: 849,
    salePrice: 649,
    rating: 4.9,
    reviewCount: 450,
    tags: ['movies', 'breaking bad', 'walter white', 'jesse pinkman', 'rv', 'crystal ship', 'heisenberg', 'cult', 'hollywood'],
    keywords: 'breaking bad walter white jesse pinkman fleetwood bounder rv crystal ship desert albuquerque amc crime'
  },
  {
    file: '1555944.png',
    title: 'JD ON WHEELS | Master Vintage Car Slump',
    subtitle: 'Tamil Cinema Legends · Thalapathy Vijay Swagger',
    category: 'Movies',
    collection: 'Tamil Cinema Legends',
    artist: 'Kollywood Fine Arts',
    subject: 'Professor JD leaning against classic vintage cruiser with sunglasses',
    badge: 'TRENDING',
    regularPrice: 899,
    salePrice: 699,
    rating: 4.9,
    reviewCount: 610,
    tags: ['movies', 'tamil', 'vijay', 'thalapathy vijay', 'master', 'kollywood', 'vintage car', 'cinema', 'action'],
    keywords: 'master professor jd thalapathy vijay vintage car sunglasses swagger kollywood tamil movie poster'
  },
  {
    file: '1555945.png',
    title: 'PATRICK BATEMAN | Bloodstain & Cleaver',
    subtitle: 'Cult Cinema · Monochromatic Crimson Splatter',
    category: 'Movies',
    collection: 'Cult Cinema',
    artist: 'Studio PINBOARD',
    subject: 'Christian Bale side profile with subtle blood spray and cleaver',
    badge: null,
    regularPrice: 849,
    salePrice: 649,
    rating: 4.8,
    reviewCount: 390,
    tags: ['movies', 'american psycho', 'patrick bateman', 'christian bale', 'blood', 'wall street', 'cult', 'hollywood'],
    keywords: 'patrick bateman christian bale american psycho bloodstain axe cleaver wall street satire cult classic'
  },
  {
    file: '1555960.png',
    title: 'IT\'S NOT ABOUT MONEY | Once Upon a Time',
    subtitle: 'Hollywood Cinema · Quentin Tarantino',
    category: 'Movies',
    collection: 'Cult Cinema',
    artist: 'Studio PINBOARD',
    subject: 'Rick Dalton and Cliff Booth cruising through vintage Hollywood 1969',
    badge: 'STAFF PICK',
    regularPrice: 899,
    salePrice: 699,
    rating: 4.9,
    reviewCount: 520,
    tags: ['movies', 'once upon a time in hollywood', 'quentin tarantino', 'brad pitt', 'leonardo dicaprio', 'hollywood', 'cinema'],
    keywords: 'once upon a time in hollywood quentin tarantino rick dalton cliff booth brad pitt leonardo dicaprio 1969 sunset boulevard'
  },
  {
    file: '1555968.png',
    title: 'ATONEMENT | The Fountain Romance',
    subtitle: 'Romantic Cinema · Green Dress Double Exposure',
    category: 'Movies',
    collection: 'Cult Cinema',
    artist: 'Studio PINBOARD',
    subject: 'Keira Knightley in iconic emerald satin dress with fountain water',
    badge: 'AESTHETIC',
    regularPrice: 849,
    salePrice: 649,
    rating: 4.9,
    reviewCount: 460,
    tags: ['movies', 'atonement', 'keira knightley', 'james mcavoy', 'green dress', 'fountain', 'hollywood', 'romance'],
    keywords: 'atonement keira knightley green dress emerald satin fountain cecilia tallis james mcavoy period romance'
  },
  {
    file: '1555969.png',
    title: 'ATONEMENT | Water Lily Reflection',
    subtitle: 'Romantic Cinema · Cinematic Macro Art',
    category: 'Movies',
    collection: 'Cult Cinema',
    artist: 'Studio PINBOARD',
    subject: 'Hand grazing water lily pond reflection in estate courtyard',
    badge: null,
    regularPrice: 799,
    salePrice: 599,
    rating: 4.8,
    reviewCount: 270,
    tags: ['movies', 'atonement', 'water lily', 'fountain', 'reflection', 'cinematic', 'hollywood', 'romance', 'aesthetic'],
    keywords: 'atonement water lily reflection estate fountain romance macro cinema visual poetry aesthetic'
  },
  {
    file: '1555970.png',
    title: 'ATONEMENT | Garden Stairs Encounter',
    subtitle: 'Romantic Cinema · Estate Garden Stairs',
    category: 'Movies',
    collection: 'Cult Cinema',
    artist: 'Studio PINBOARD',
    subject: 'Robbie and Cecilia on stone garden stairs in golden late afternoon sun',
    badge: null,
    regularPrice: 849,
    salePrice: 649,
    rating: 4.9,
    reviewCount: 340,
    tags: ['movies', 'atonement', 'keira knightley', 'james mcavoy', 'garden', 'stairs', 'hollywood', 'romance'],
    keywords: 'atonement robbie cecilia garden stairs golden sunlight stone estate romance period drama film'
  },
  {
    file: '1555983.png',
    title: 'RUST COHLE | Lone Star Beer & Smoke',
    subtitle: 'Cult Television · True Detective Season 1',
    category: 'Movies',
    collection: 'Cult Cinema',
    artist: 'Studio PINBOARD',
    subject: 'Matthew McConaughey as Rustin Cohle folding Lone Star tin can man',
    badge: 'POPULAR',
    regularPrice: 899,
    salePrice: 699,
    rating: 5.0,
    reviewCount: 820,
    tags: ['movies', 'true detective', 'rust cohle', 'matthew mcconaughey', 'lone star', 'time is a flat circle', 'hollywood', 'hbo'],
    keywords: 'true detective rust cohle matthew mcconaughey lone star beer time is a flat circle hbo crime noir nihilism'
  },
  {
    file: '1556445.png',
    title: 'LOVE & LOSS | Atonement Vintage Editorial',
    subtitle: 'Romantic Cinema · Typographic Vignette',
    category: 'Movies',
    collection: 'Cult Cinema',
    artist: 'Studio PINBOARD',
    subject: 'Vintage serif typography quotes over poignant portrait of Robbie and Cecilia',
    badge: null,
    regularPrice: 799,
    salePrice: 599,
    rating: 4.8,
    reviewCount: 230,
    tags: ['movies', 'atonement', 'love', 'editorial', 'typography', 'hollywood', 'romance', 'vintage'],
    keywords: 'atonement love and loss typography vintage editorial keira knightley james mcavoy romantic drama'
  },
  {
    file: '1556706.png',
    title: 'SPIDER-MAN | Mask in Hand',
    subtitle: 'Marvel Cinema · Emotional Burden Print',
    category: 'Movies',
    collection: 'Marvel & Cinema',
    artist: 'PINBOARD Marvel Studio',
    subject: 'Peter Parker holding spider mask looking out over midnight skyline',
    badge: null,
    regularPrice: 849,
    salePrice: 649,
    rating: 4.8,
    reviewCount: 320,
    tags: ['movies', 'marvel', 'spiderman', 'spider-man', 'mask', 'peter parker', 'superhero', 'comic', 'action'],
    keywords: 'spider-man mask in hand peter parker responsibility marvel superhero midnight city skyline emotion'
  },
  {
    file: '1556723.png',
    title: 'THEY CALL ME BABA YAGA | John Wick',
    subtitle: 'Action Cinema · Tailored Kevlar Print',
    category: 'Movies',
    collection: 'Cult Cinema',
    artist: 'Continental Archives',
    subject: 'John Wick adjusting black tie in continental glass pavilion',
    badge: 'TRENDING',
    regularPrice: 849,
    salePrice: 649,
    rating: 4.9,
    reviewCount: 560,
    tags: ['movies', 'john wick', 'baba yaga', 'keanu reeves', 'continental', 'suit', 'action', 'hollywood'],
    keywords: 'they call me baba yaga john wick keanu reeves continental hotel tailored suit tie assassin action'
  },
  {
    file: '1556727.png',
    title: 'MAN OF STEEL | Heavy Shadow Silhouette',
    subtitle: 'DC Universe · Zack Snyder Aesthetic',
    category: 'Movies',
    collection: 'DC & Gotham',
    artist: 'DC Cinematic Studio',
    subject: 'Superman in deep high-contrast shadow with glowing red heat vision eyes',
    badge: 'HOT',
    regularPrice: 899,
    salePrice: 699,
    rating: 4.9,
    reviewCount: 510,
    tags: ['movies', 'dc', 'superman', 'man of steel', 'heat vision', 'zack snyder', 'superhero', 'action', 'sci-fi'],
    keywords: 'superman man of steel heat vision red eyes heavy shadow zack snyder dc comics superhero dark'
  },
  {
    file: '1556729.png',
    title: '\'96 THE MOVIE | Ram & Janu Comic Strip',
    subtitle: 'Tamil Cinema Classics · Vijay Sethupathi & Trisha',
    category: 'Movies',
    collection: 'Tamil Cinema Legends',
    artist: 'Kollywood Fine Arts',
    subject: 'Ram and Janu yellow dupatta and photography camera comic moments',
    badge: 'POPULAR',
    regularPrice: 899,
    salePrice: 699,
    rating: 5.0,
    reviewCount: 970,
    tags: ['movies', 'tamil', '96 the movie', 'ram and janu', 'vijay sethupathi', 'trisha', 'kollywood', 'romance', 'cinema'],
    keywords: '96 the movie ram janu vijay sethupathi trisha yellow dupatta the life of ram prem kumar kollywood romance'
  },
  {
    file: '1556901.png',
    title: 'DOOM | Sovereign of Latveria',
    subtitle: 'Marvel Comics · Crown & Mask Print',
    category: 'Movies',
    collection: 'Marvel & Cinema',
    artist: 'Latverian State Archive',
    subject: 'Doctor Victor von Doom wearing Latverian royal seal and golden cloak clasp',
    badge: null,
    regularPrice: 849,
    salePrice: 649,
    rating: 4.9,
    reviewCount: 430,
    tags: ['movies', 'marvel', 'doctor doom', 'victor von doom', 'fantastic four', 'latveria', 'comic', 'supervillain'],
    keywords: 'doctor doom victor von doom monarch sovereign latveria iron mask marvel fantastic four comic art'
  },
  {
    file: '1556956.png',
    title: 'PATRICK | American Psycho Red Type',
    subtitle: 'Cult Cinema · Minimalist Red Typography',
    category: 'Movies',
    collection: 'Cult Cinema',
    artist: 'Studio PINBOARD',
    subject: 'Patrick Bateman silhouette with bold crimson typography overlay',
    badge: null,
    regularPrice: 849,
    salePrice: 649,
    rating: 4.8,
    reviewCount: 310,
    tags: ['movies', 'american psycho', 'patrick bateman', 'christian bale', 'typography', 'red', 'cult', 'hollywood'],
    keywords: 'patrick bateman american psycho christian bale bold red typography minimalist wall street cult film'
  },
  {
    file: '1557082.png',
    title: 'I NEED YOU | Peaky Blinders Thomas & Grace',
    subtitle: 'British Television · Shelby Family Print',
    category: 'Movies',
    collection: 'Cult Cinema',
    artist: 'Garrison Lane Archives',
    subject: 'Thomas Shelby and Grace Burgess in smoke-filled Birmingham pub',
    badge: 'TRENDING',
    regularPrice: 899,
    salePrice: 699,
    rating: 4.9,
    reviewCount: 680,
    tags: ['movies', 'peaky blinders', 'thomas shelby', 'cillian murphy', 'grace burgess', 'by order of the peaky blinders', 'hollywood', 'drama'],
    keywords: 'peaky blinders thomas shelby cillian murphy grace burgess garrison pub birmingham flat cap crime drama'
  },
  {
    file: '1557084.png',
    title: 'BROTHERHOOD | Cliff & Rick Cadillac',
    subtitle: 'Hollywood Cinema · Once Upon a Time in Hollywood',
    category: 'Movies',
    collection: 'Cult Cinema',
    artist: 'Studio PINBOARD',
    subject: 'Cliff Booth driving Rick Dalton in 1966 Cadillac DeVille in California sun',
    badge: null,
    regularPrice: 849,
    salePrice: 649,
    rating: 4.9,
    reviewCount: 420,
    tags: ['movies', 'once upon a time in hollywood', 'brad pitt', 'leonardo dicaprio', 'cliff booth', 'rick dalton', 'cadillac', 'hollywood'],
    keywords: 'brotherhood once upon a time in hollywood brad pitt leonardo dicaprio cadillac deville quentin tarantino'
  },
  {
    file: '1557102.png',
    title: 'SYMBOL OF HOPE | Superman Cloud Horizon',
    subtitle: 'DC Universe · Celestial Sunrise Print',
    category: 'Movies',
    collection: 'DC & Gotham',
    artist: 'DC Cinematic Studio',
    subject: 'Superman soaring upwards through billowing golden cumulus clouds',
    badge: 'POPULAR',
    regularPrice: 849,
    salePrice: 649,
    rating: 4.8,
    reviewCount: 390,
    tags: ['movies', 'dc', 'superman', 'symbol of hope', 'clark kent', 'clouds', 'sunrise', 'superhero', 'sci-fi'],
    keywords: 'symbol of hope superman soaring clouds sunrise golden rays clark kent dc comics superhero flight'
  },
  {
    file: '1557131.png',
    title: 'BARE MINIMUM | Scarlet Witch Wanda',
    subtitle: 'Marvel Cinema · Chaos Magic Scarlet Print',
    category: 'Movies',
    collection: 'Marvel & Cinema',
    artist: 'PINBOARD Marvel Studio',
    subject: 'Wanda Maximoff Scarlet Witch crown with crimson chaos magic swirling',
    badge: 'HOT',
    regularPrice: 899,
    salePrice: 699,
    rating: 5.0,
    reviewCount: 890,
    tags: ['movies', 'marvel', 'scarlet witch', 'wanda maximoff', 'elizabeth olsen', 'chaos magic', 'avengers', 'superhero'],
    keywords: 'scarlet witch wanda maximoff elizabeth olsen chaos magic wanda vision multivese of madness marvel'
  },
  {
    file: '1557153.png',
    title: 'DEVADAS & CHANDRA | Vintage Romance Duo',
    subtitle: 'Tamil Cinema Classics · Timeless Embrace',
    category: 'Movies',
    collection: 'Tamil Cinema Legends',
    artist: 'Kollywood Fine Arts',
    subject: 'Devadas and Chandra romantic profile in vintage sepia tones',
    badge: null,
    regularPrice: 799,
    salePrice: 599,
    rating: 4.8,
    reviewCount: 280,
    tags: ['movies', 'tamil', 'devadas', 'chandra', 'kollywood', 'vintage', 'romance', 'classic', 'cinema'],
    keywords: 'devadas chandra vintage romance sepia tamil cinema kollywood classic tragic lovers timeless art'
  },
  {
    file: '1557157.png',
    title: 'PARISUTHA KAADHAL | Pure Love Tamil Romance',
    subtitle: 'Tamil Cinema Classics · Serene Romance Print',
    category: 'Movies',
    collection: 'Tamil Cinema Legends',
    artist: 'Kollywood Fine Arts',
    subject: 'Romantic sunset silhouette with Tamil calligraphy typography',
    badge: 'AESTHETIC',
    regularPrice: 799,
    salePrice: 599,
    rating: 4.8,
    reviewCount: 310,
    tags: ['movies', 'tamil', 'parisutha kaadhal', 'pure love', 'kollywood', 'calligraphy', 'romance', 'cinema'],
    keywords: 'parisutha kaadhal pure love tamil romance kollywood calligraphy sunset silhouette emotional cinema'
  },
  {
    file: '1557173.png',
    title: 'CHANDRA | Red Velvet Veil',
    subtitle: 'Tamil Cinema Classics · Crimson Elegance Print',
    category: 'Movies',
    collection: 'Tamil Cinema Legends',
    artist: 'Kollywood Fine Arts',
    subject: 'Chandra looking through sheer red velvet veil with gold jewelry',
    badge: null,
    regularPrice: 799,
    salePrice: 599,
    rating: 4.8,
    reviewCount: 260,
    tags: ['movies', 'tamil', 'chandra', 'kollywood', 'red veil', 'vintage', 'elegance', 'classic', 'cinema'],
    keywords: 'chandra red velvet veil gold jewelry vintage kollywood tamil cinema elegance traditional beauty'
  },
  {
    file: '1557175.png',
    title: 'CHANDRA | Black Saree & Sunglasses',
    subtitle: 'Tamil Cinema Classics · Retro Chic Icon',
    category: 'Movies',
    collection: 'Tamil Cinema Legends',
    artist: 'Kollywood Fine Arts',
    subject: 'Chandra wearing modern black saree with dark oval sunglasses',
    badge: 'STAFF PICK',
    regularPrice: 849,
    salePrice: 649,
    rating: 4.9,
    reviewCount: 410,
    tags: ['movies', 'tamil', 'chandra', 'kollywood', 'black saree', 'sunglasses', 'retro chic', 'classic'],
    keywords: 'chandra black saree dark sunglasses retro chic modern vintage fusion kollywood tamil cinema icon'
  },
  {
    file: 'A4 Posters [55573EA].png',
    title: 'SPIDER-MAN | Tame Impala Currents Tribute',
    subtitle: 'Marvel Cinema · Psychedelic Currents Edition',
    category: 'Movies',
    collection: 'Marvel & Cinema',
    artist: 'PINBOARD Marvel Studio',
    subject: 'Spider-Man mask integrated into swirling purple Tame Impala currents',
    badge: 'HOT',
    regularPrice: 849,
    salePrice: 649,
    rating: 4.9,
    reviewCount: 530,
    tags: ['movies', 'marvel', 'spiderman', 'spider-man', 'tame impala', 'currents', 'psychedelic', 'superhero', 'animation'],
    keywords: 'spider-man tame impala currents psychedelic purple waves peter parker marvel album mashup poster'
  },
  {
    file: 'A4 Posters [5FE0EB5].png',
    title: 'MASTER JD | Green Neon Halo',
    subtitle: 'Tamil Cinema Legends · Cyber Last Supper',
    category: 'Movies',
    collection: 'Tamil Cinema Legends',
    artist: 'Kollywood Fine Arts',
    subject: 'Thalapathy Vijay with cat and glowing lime-green halo ring',
    badge: 'POPULAR',
    regularPrice: 899,
    salePrice: 699,
    rating: 5.0,
    reviewCount: 880,
    tags: ['movies', 'tamil', 'vijay', 'thalapathy vijay', 'master', 'neon halo', 'kollywood', 'cinema', 'action'],
    keywords: 'master thalapathy vijay green neon halo cat sunglasses last supper lokesh kanagaraj kollywood'
  },
  {
    file: 'A4 Posters [697243A].png',
    title: 'BROTHERHOOD | Leonardo & Brad Vintage Sunset',
    subtitle: 'Hollywood Cinema · Retro Boulevard Edition',
    category: 'Movies',
    collection: 'Cult Cinema',
    artist: 'Studio PINBOARD',
    subject: 'Brad Pitt and Leonardo DiCaprio leaning on hood of sports roadster',
    badge: 'TRENDING',
    regularPrice: 849,
    salePrice: 649,
    rating: 4.9,
    reviewCount: 470,
    tags: ['movies', 'once upon a time in hollywood', 'brad pitt', 'leonardo dicaprio', 'hollywood', 'cinema', 'brotherhood'],
    keywords: 'brotherhood leonardo dicaprio brad pitt once upon a time in hollywood quentin tarantino retro cinema'
  },

  // ==========================================
  // 🚗 CARS (Supercars, Hypercars, Racing, Lightning McQueen, Porsche, Ferrari, BMW)
  // ==========================================
  {
    file: '1514077.png',
    title: 'LIGHTNING McQUEEN | Skyfall Through Clouds',
    subtitle: 'Automotive Animation · #95 Racing Print',
    category: 'Cars',
    collection: 'Supercars & Speed',
    artist: 'Piston Cup Archives',
    subject: 'Lightning McQueen #95 freefalling through golden sunset clouds',
    badge: 'POPULAR',
    regularPrice: 849,
    salePrice: 649,
    rating: 4.9,
    reviewCount: 510,
    tags: ['cars', 'lightning mcqueen', 'cars movie', 'pixar', 'piston cup', 'rust-eze', 'racing', 'supercars', 'speed'],
    keywords: 'lightning mcqueen 95 cars movie pixar rust-eze racing skyfall clouds red racecar speed automotive'
  },
  {
    file: '1514085.png',
    title: 'BMW E30 M3 | White Smoke Drift',
    subtitle: 'Motorsport Heritage · Bavarian Classic',
    category: 'Cars',
    collection: 'Supercars & Speed',
    artist: 'M-Power Atelier',
    subject: 'BMW E30 M3 sliding through thick white tire smoke on tarmac',
    badge: 'HOT',
    regularPrice: 899,
    salePrice: 699,
    rating: 5.0,
    reviewCount: 760,
    tags: ['cars', 'bmw', 'bmw e30 m3', 'm-power', 'drift', 'smoke', 'german', 'supercars', 'motorsport'],
    keywords: 'bmw e30 m3 bmw m power drift white tire smoke tarmac german motorsport heritage racing classic'
  },
  {
    file: '1553196.jpg',
    title: 'LIGHTNING McQUEEN | Red Flash & Bolt',
    subtitle: 'Automotive Animation · Speed is My Fuel',
    category: 'Cars',
    collection: 'Supercars & Speed',
    artist: 'Piston Cup Archives',
    subject: 'Lightning McQueen accelerating with electric yellow lightning bolt graphic',
    badge: null,
    regularPrice: 849,
    salePrice: 649,
    rating: 4.8,
    reviewCount: 380,
    tags: ['cars', 'lightning mcqueen', 'cars movie', 'racing', 'lightning bolt', 'speed', 'rust-eze', 'supercars'],
    keywords: 'lightning mcqueen 95 lightning bolt red racecar speed rust-eze piston cup pixar racing car automotive'
  },
  {
    file: '1555889.png',
    title: 'LIGHTNING McQUEEN | Dark Shadow Silhouette',
    subtitle: 'Automotive Animation · Midnight Circuit Edition',
    category: 'Cars',
    collection: 'Supercars & Speed',
    artist: 'Piston Cup Archives',
    subject: 'Minimalist low-light aerodynamic silhouette of #95 with glowing headlights',
    badge: null,
    regularPrice: 849,
    salePrice: 649,
    rating: 4.8,
    reviewCount: 290,
    tags: ['cars', 'lightning mcqueen', 'silhouette', 'racing', 'speed', 'supercars', 'hypercars', 'piston cup'],
    keywords: 'lightning mcqueen silhouette dark shadows headlights racing racecar aerodynamic speed cars 95'
  },
  {
    file: '1555891.png',
    title: 'RUST-EZE RACING #95 | Wet Track Reflection',
    subtitle: 'Automotive Animation · Neon Rain Race',
    category: 'Cars',
    collection: 'Supercars & Speed',
    artist: 'Piston Cup Archives',
    subject: 'Lightning McQueen reflected on soaked wet track with stadium floodlights',
    badge: 'TRENDING',
    regularPrice: 849,
    salePrice: 649,
    rating: 4.9,
    reviewCount: 440,
    tags: ['cars', 'lightning mcqueen', 'rust-eze', 'wet track', 'reflection', 'racing', 'supercars', 'speed'],
    keywords: 'lightning mcqueen rust-eze 95 wet track reflection rain stadium neon racing speed racecar'
  },
  {
    file: '1555982.png',
    title: 'SUPERCHARGED #95 | Ground-Hugging Slick Tire',
    subtitle: 'Automotive Animation · Track Engineering Print',
    category: 'Cars',
    collection: 'Supercars & Speed',
    artist: 'Piston Cup Archives',
    subject: 'Macro wheel well shot of Lightyear racing slick tire and red side skirt',
    badge: null,
    regularPrice: 849,
    salePrice: 649,
    rating: 4.8,
    reviewCount: 310,
    tags: ['cars', 'lightning mcqueen', 'lightyear tires', 'racing', 'supercars', 'speed', 'track', 'aerodynamic'],
    keywords: 'lightning mcqueen lightyear tires slick tire macro aero red side skirt supercharged racecar speed'
  },
  {
    file: '1556440.png',
    title: '95 SPEED IS MY FUEL | Aerodynamic Red Fin',
    subtitle: 'Automotive Animation · Rear Wing Downforce',
    category: 'Cars',
    collection: 'Supercars & Speed',
    artist: 'Piston Cup Archives',
    subject: 'Rear wing aerodynamic downforce and dual exhaust flame of #95',
    badge: null,
    regularPrice: 849,
    salePrice: 649,
    rating: 4.8,
    reviewCount: 330,
    tags: ['cars', 'lightning mcqueen', 'rear wing', 'downforce', 'racing', 'supercars', 'speed', 'exhaust'],
    keywords: 'lightning mcqueen speed is my fuel rear wing downforce red fin aerodynamic racecar 95 racing'
  },
  {
    file: '1557527.png',
    title: 'PORSCHE 911 GT3 RS | Race-Spec Aero on Bold Red',
    subtitle: 'Stuttgart Precision · Weissach Package Print',
    category: 'Cars',
    collection: 'Supercars & Speed',
    artist: 'Weissach Motorsport Studio',
    subject: 'Porsche 911 GT3 RS swan-neck rear wing on vivid crimson canvas',
    badge: 'HOT',
    regularPrice: 999,
    salePrice: 799,
    rating: 5.0,
    reviewCount: 890,
    tags: ['cars', 'porsche', 'porsche 911 gt3 rs', 'gt3 rs', 'weissach', 'supercars', 'hypercars', 'germany', 'speed'],
    keywords: 'porsche 911 gt3 rs gt3rs weissach package stuttgart swan-neck wing racecar supercar hypercars speed red'
  },
  {
    file: '1557528.png',
    title: 'FERRARI 250 GTO | Minimalist Rosso Corsa',
    subtitle: 'Maranello Heritage · Sculptural Legend',
    category: 'Cars',
    collection: 'Supercars & Speed',
    artist: 'Maranello Fine Art',
    subject: 'Ferrari 250 GTO aerodynamic profile on pure white and crimson wedge',
    badge: 'STAFF PICK',
    regularPrice: 999,
    salePrice: 799,
    rating: 5.0,
    reviewCount: 940,
    tags: ['cars', 'ferrari', 'ferrari 250 gto', 'maranello', 'rosso corsa', 'supercars', 'hypercars', 'italian', 'racing'],
    keywords: 'ferrari 250 gto maranello rosso corsa italian supercar vintage racing sculpture minimalist red white wedge'
  },
  {
    file: '1557529.png',
    title: 'PORSCHE 911 GT3 RS | Pure White Supercar on Crimson',
    subtitle: 'Stuttgart Precision · Track Weapon Edition',
    category: 'Cars',
    collection: 'Supercars & Speed',
    artist: 'Weissach Motorsport Studio',
    subject: 'Pure white Porsche 911 GT3 RS silhouette against bold crimson split',
    badge: 'BESTSELLER',
    regularPrice: 999,
    salePrice: 799,
    rating: 5.0,
    reviewCount: 1020,
    tags: ['cars', 'porsche', 'porsche 911 gt3 rs', 'gt3 rs', 'supercars', 'hypercars', 'white', 'crimson', 'speed'],
    keywords: 'porsche 911 gt3 rs pure white supercar crimson contrast stuttgart track weapon racing aero speed'
  },

  // ==========================================
  // 💪 MOTIVATION (Discipline, Mindset, Stoicism, Aesthetic Nature, Quotes)
  // ==========================================
  {
    file: '1513632.png',
    title: 'SWEATER WEATHER | Coastal Wave Solitude',
    subtitle: 'Mindfulness & Nature · Pacific Solitude',
    category: 'Motivation',
    collection: 'Mindset & Stoicism',
    artist: 'Pacific Visuals',
    subject: 'Lone figure standing on rugged seaside cliff overlooking misty waves',
    badge: 'CALM',
    regularPrice: 799,
    salePrice: 599,
    rating: 4.8,
    reviewCount: 310,
    tags: ['motivation', 'mindfulness', 'calm', 'solitude', 'ocean', 'waves', 'stoic', 'peace', 'nature'],
    keywords: 'sweater weather coastal wave solitude ocean cliff mindfulness calm peace reflection stoic nature'
  },
  {
    file: '1514059.png',
    title: 'INTO THE WILD | Magic Bus 142',
    subtitle: 'Freedom & Philosophy · Alexander Supertramp',
    category: 'Motivation',
    collection: 'Mindset & Stoicism',
    artist: 'Wilderness Press',
    subject: 'Alexander Supertramp Christopher McCandless atop Fairbanks Bus 142',
    badge: 'POPULAR',
    regularPrice: 849,
    salePrice: 649,
    rating: 4.9,
    reviewCount: 520,
    tags: ['motivation', 'into the wild', 'alexander supertramp', 'magic bus 142', 'freedom', 'alaska', 'mindset', 'adventure'],
    keywords: 'into the wild alexander supertramp christopher mccandless magic bus 142 alaska wilderness freedom mindset'
  },
  {
    file: '1514166.png',
    title: 'WHAT IF IT WORKS | Bold Determination',
    subtitle: 'Mindset & Drive · Unshakable Focus',
    category: 'Motivation',
    collection: 'Mindset & Stoicism',
    artist: 'Discipline Press',
    subject: 'Bold black and white determination typography What If It Works',
    badge: 'HOT',
    regularPrice: 799,
    salePrice: 599,
    rating: 4.9,
    reviewCount: 460,
    tags: ['motivation', 'discipline', 'hustle', 'success', 'mindset', 'focus', 'determination', 'quote'],
    keywords: 'what if it works bold determination mindset focus hustle discipline ambition success typography quote'
  },
  {
    file: '1514232.png',
    title: 'BE YOURSELF | Stage Spotlight Authenticity',
    subtitle: 'Mindset & Courage · True Identity Print',
    category: 'Motivation',
    collection: 'Mindset & Stoicism',
    artist: 'Authentic Studio',
    subject: 'Silhouette stepping into brilliant stage spotlight with Be Yourself motto',
    badge: null,
    regularPrice: 799,
    salePrice: 599,
    rating: 4.8,
    reviewCount: 290,
    tags: ['motivation', 'mindfulness', 'authenticity', 'be yourself', 'courage', 'mindset', 'leadership', 'focus'],
    keywords: 'be yourself stage spotlight authenticity courage confidence leadership self belief mindset poster'
  },
  {
    file: '1551532.jpg',
    title: 'DISCIPLINE MAKES YOU UNFORGETTABLE | CR7',
    subtitle: 'Athletic Drive · Cristiano Ronaldo Standard',
    category: 'Motivation',
    collection: 'Mindset & Stoicism',
    artist: 'Discipline Press',
    subject: 'Cristiano Ronaldo physique training in torrential stadium rain',
    badge: 'BESTSELLER',
    regularPrice: 899,
    salePrice: 699,
    rating: 5.0,
    reviewCount: 1140,
    tags: ['motivation', 'discipline', 'gym & fitness', 'fitness', 'gym', 'cristiano ronaldo', 'cr7', 'hustle', 'legends'],
    keywords: 'discipline makes you unforgettable cristiano ronaldo cr7 gym fitness training physique workout hustle legends'
  },
  {
    file: '1554426.jpg',
    title: 'RISK IS BETTER THAN REGRET | Distressed Block',
    subtitle: 'Mindset & Courage · Vintage Letterpress',
    category: 'Motivation',
    collection: 'Mindset & Stoicism',
    artist: 'Discipline Press',
    subject: 'Distressed woodblock typography Risk Is Better Than Regret',
    badge: 'POPULAR',
    regularPrice: 799,
    salePrice: 599,
    rating: 4.8,
    reviewCount: 380,
    tags: ['motivation', 'hustle', 'risk', 'success', 'mindset', 'courage', 'discipline', 'typography'],
    keywords: 'risk is better than regret courage hustle mindset discipline ambition success vintage letterpress quote'
  },
  {
    file: '1554532.png',
    title: 'IT\'S ONLY YOU | Moonlight Ocean Horizon',
    subtitle: 'Stoic Solitude · Self Mastery Print',
    category: 'Motivation',
    collection: 'Mindset & Stoicism',
    artist: 'Stoic Visuals',
    subject: 'At the end there is no one it is only you against midnight ocean moon',
    badge: 'AESTHETIC',
    regularPrice: 849,
    salePrice: 649,
    rating: 4.9,
    reviewCount: 420,
    tags: ['motivation', 'discipline', 'mindfulness', 'stoic', 'ocean', 'solitude', 'mindset', 'self mastery'],
    keywords: 'at the end there is no one its only you moonlight ocean horizon stoic solitude self mastery mindset discipline'
  },
  {
    file: '1555984.png',
    title: 'GOLDEN HOUR SWELL | The Ocean Horizon',
    subtitle: 'Mindfulness & Nature · Liquid Gold Water',
    category: 'Motivation',
    collection: 'Mindset & Stoicism',
    artist: 'Pacific Visuals',
    subject: 'Crest of massive rolling dark wave illuminated by blinding golden sunlight',
    badge: null,
    regularPrice: 849,
    salePrice: 649,
    rating: 4.8,
    reviewCount: 330,
    tags: ['motivation', 'mindfulness', 'calm', 'ocean', 'waves', 'golden hour', 'nature', 'peace', 'mindset'],
    keywords: 'golden hour swell ocean waves rolling water liquid gold sunlight horizon calm mindfulness nature'
  },
  {
    file: '1555986.png',
    title: 'DEEP OCEAN LUMINESCENCE | Midnight Calm',
    subtitle: 'Mindfulness & Nature · Abyssal Specular',
    category: 'Motivation',
    collection: 'Mindset & Stoicism',
    artist: 'Pacific Visuals',
    subject: 'Deep blue dark ocean ripple reflecting pinpoint stars and moonlight',
    badge: null,
    regularPrice: 799,
    salePrice: 599,
    rating: 4.8,
    reviewCount: 280,
    tags: ['motivation', 'mindfulness', 'calm', 'ocean', 'deep water', 'midnight', 'nature', 'stoic', 'mindset'],
    keywords: 'deep ocean luminescence midnight calm dark water ripple stars moonlight mindfulness peace stoic'
  },
  {
    file: '1556441.png',
    title: 'SPARTAN | Blood Moon Warrior Discipline',
    subtitle: 'Ancient Stoicism · Warrior Mindset',
    category: 'Motivation',
    collection: 'Mindset & Stoicism',
    artist: 'Spartan Atelier',
    subject: 'Corinthian bronze spartan helmet framed by blood red crescent moon',
    badge: 'HOT',
    regularPrice: 899,
    salePrice: 699,
    rating: 4.9,
    reviewCount: 620,
    tags: ['motivation', 'discipline', 'gym & fitness', 'spartan', 'warrior', 'stoic', 'legends', 'mindset'],
    keywords: 'spartan warrior helmet blood moon discipline stoic strength courage ancient warrior gym fitness mindset'
  },
  {
    file: '1556915.png',
    title: 'THERE IS NO TOMORROW | Rocky Balboa Grit',
    subtitle: 'Championship Drive · Philadelphia Heavyweight',
    category: 'Motivation',
    collection: 'Mindset & Stoicism',
    artist: 'Discipline Press',
    subject: 'Rocky Balboa boxing gloves raised on Philadelphia art museum steps',
    badge: 'BESTSELLER',
    regularPrice: 899,
    salePrice: 699,
    rating: 5.0,
    reviewCount: 890,
    tags: ['motivation', 'discipline', 'gym & fitness', 'hustle', 'rocky balboa', 'boxing', 'legends', 'success'],
    keywords: 'there is no tomorrow rocky balboa sylvester stallone boxing gym workout philadelphia grit discipline champions'
  },
  {
    file: '1556930.png',
    title: 'YOU VS YOU | Face Your Stronger Self',
    subtitle: 'Self Mastery · The Internal Battle',
    category: 'Motivation',
    collection: 'Mindset & Stoicism',
    artist: 'Discipline Press',
    subject: 'Athlete facing towering mirror reflection You vs You typography',
    badge: 'POPULAR',
    regularPrice: 849,
    salePrice: 649,
    rating: 4.9,
    reviewCount: 510,
    tags: ['motivation', 'discipline', 'gym & fitness', 'fitness', 'gym', 'you vs you', 'hustle', 'mindset'],
    keywords: 'you vs you internal battle face your stronger self discipline gym fitness workout mindset self mastery'
  },
  {
    file: '1556935.png',
    title: 'CONSISTENCY | Heavy Tire Flip Training',
    subtitle: 'Gym & Fitness · Raw Industrial Conditioning',
    category: 'Motivation',
    collection: 'Mindset & Stoicism',
    artist: 'Discipline Press',
    subject: 'Heavy 300kg industrial tractor tire flip in gritty warehouse gym',
    badge: null,
    regularPrice: 849,
    salePrice: 649,
    rating: 4.8,
    reviewCount: 370,
    tags: ['motivation', 'discipline', 'gym & fitness', 'gym', 'fitness', 'consistency', 'tire flip', 'workout', 'hustle'],
    keywords: 'consistency heavy tire flip gym fitness crossfit strength training raw grit sweat discipline workout'
  },
  {
    file: 'p1.png',
    title: 'APOCALYPSE | Cigarettes After Sex',
    subtitle: 'Ethereal Aesthetic · Dream Pop Noir',
    category: 'Motivation',
    collection: 'Mindset & Stoicism',
    artist: 'Dream Pop Visuals',
    subject: 'Billowing ethereal white smoke in deep void with CAS Apocalypse lyrics',
    badge: 'AESTHETIC',
    regularPrice: 799,
    salePrice: 599,
    rating: 4.9,
    reviewCount: 440,
    tags: ['motivation', 'mindfulness', 'calm', 'cigarettes after sex', 'apocalypse', 'aesthetic', 'music', 'dream pop'],
    keywords: 'cigarettes after sex apocalypse your lips my lips apocalypse ethereal smoke dream pop calm aesthetic'
  },

  // ==========================================
  // 🎮 GAMING (Red Dead Redemption 2, GTA 6, Esports, Gaming Culture)
  // ==========================================
  {
    file: '1555762.png',
    title: 'ARTHUR MORGAN | Outlaw in the Shadows',
    subtitle: 'Rockstar Games · Red Dead Redemption II',
    category: 'Gaming',
    collection: 'Red Dead & GTA Legends',
    artist: 'Van der Linde Gallery',
    subject: 'Arthur Morgan aiming Cattleman revolver from misty frontier forest',
    badge: 'HOT',
    regularPrice: 899,
    salePrice: 699,
    rating: 5.0,
    reviewCount: 1180,
    tags: ['gaming', 'red dead redemption', 'arthur morgan', 'rdr2', 'rockstar games', 'outlaw', 'playstation', 'xbox'],
    keywords: 'arthur morgan red dead redemption 2 rdr2 rockstar games outlaw van der linde revolver frontier gaming'
  },
  {
    file: '1555764.png',
    title: 'GRAND THEFT AUTO VI | Jason & Lucia Vice City',
    subtitle: 'Rockstar Games · Vice City Neon Sunset',
    category: 'Gaming',
    collection: 'Red Dead & GTA Legends',
    artist: 'Rockstar Visuals',
    subject: 'Jason and Lucia seated on car hood against iconic pink Vice City skyline',
    badge: 'BESTSELLER',
    regularPrice: 949,
    salePrice: 749,
    rating: 5.0,
    reviewCount: 1650,
    tags: ['gaming', 'gta', 'gta vi', 'vice city', 'jason and lucia', 'rockstar games', 'playstation', 'xbox'],
    keywords: 'gta vi grand theft auto 6 vice city jason lucia leonida rockstar games pink sunset palm trees gaming'
  },
  {
    file: '1556993.png',
    title: 'I GAVE YOU ALL I HAD | Arthur Morgan Sunset',
    subtitle: 'Rockstar Games · Emotional Climax Print',
    category: 'Gaming',
    collection: 'Red Dead & GTA Legends',
    artist: 'Van der Linde Gallery',
    subject: 'Arthur Morgan gazing at golden rising sun atop mountain peak',
    badge: 'STAFF PICK',
    regularPrice: 899,
    salePrice: 699,
    rating: 5.0,
    reviewCount: 1390,
    tags: ['gaming', 'red dead redemption', 'arthur morgan', 'rdr2', 'may i stand unshaken', 'rockstar games', 'playstation', 'xbox'],
    keywords: 'arthur morgan i gave you all i had may i stand unshaken sunset mountain high honor rdr2 red dead redemption 2'
  },
  {
    file: '1556996.png',
    title: 'ARTHUR MORGAN | Outlaw Legend Profile',
    subtitle: 'Rockstar Games · Sepia Charcoal Vignette',
    category: 'Gaming',
    collection: 'Red Dead & GTA Legends',
    artist: 'Van der Linde Gallery',
    subject: 'Charcoal and sepia illustrated profile of Arthur Morgan with felt hat',
    badge: null,
    regularPrice: 849,
    salePrice: 649,
    rating: 4.9,
    reviewCount: 520,
    tags: ['gaming', 'red dead redemption', 'arthur morgan', 'rdr2', 'outlaw', 'rockstar games', 'playstation', 'xbox'],
    keywords: 'arthur morgan outlaw legend profile hat felt hat rdr2 red dead redemption 2 sketch charcoal gaming'
  },
  {
    file: 'file_00000000d1a482118837991a9779439a.png',
    title: 'ARTHUR MORGAN | Outlaw. Legend. Gunslinger.',
    subtitle: 'Rockstar Games · Minimalist Western Typography',
    category: 'Gaming',
    collection: 'Red Dead & GTA Legends',
    artist: 'Van der Linde Gallery',
    subject: 'Arthur Morgan silhouette with heavy western slab typography and eagle in flight',
    badge: 'TRENDING',
    regularPrice: 899,
    salePrice: 699,
    rating: 4.9,
    reviewCount: 670,
    tags: ['gaming', 'red dead redemption', 'arthur morgan', 'rdr2', 'rockstar games', 'gunslinger', 'playstation', 'xbox'],
    keywords: 'arthur morgan outlaw legend gunslinger red dead redemption 2 rdr2 rockstar games western typography poster'
  },

  // ==========================================
  // ⚽ SPORTS (Football, Messi, Ronaldo, Champions, Boxing)
  // ==========================================
  {
    file: '1514167.png',
    title: 'THE COMEBACK | Rocky Balboa World Champion',
    subtitle: 'Boxing Legends · Heavyweight Champion of the World',
    category: 'Sports',
    collection: 'Sports Icons',
    artist: 'Championship Ring Atelier',
    subject: 'Rocky Balboa bruised and victorious with gold heavyweight title belt',
    badge: 'POPULAR',
    regularPrice: 849,
    salePrice: 649,
    rating: 4.9,
    reviewCount: 440,
    tags: ['sports', 'boxing', 'rocky balboa', 'champion', 'heavyweight', 'comeback', 'athlete', 'sports icons'],
    keywords: 'rocky balboa boxing champion heavyweight title comeback sylvester stallone boxing ring athlete sports'
  },
  {
    file: '1551192.png',
    title: 'WHEN THE DREAM BECAME IMMORTAL | Messi 2022',
    subtitle: 'Football Legends · FIFA World Cup Champions',
    category: 'Sports',
    collection: 'Football Legends',
    artist: 'Estadio Visuals',
    subject: 'Lionel Messi kissing the golden FIFA World Cup trophy in Qatar',
    badge: 'BESTSELLER',
    regularPrice: 999,
    salePrice: 799,
    rating: 5.0,
    reviewCount: 1980,
    tags: ['sports', 'football', 'messi', 'lionel messi', 'argentina', 'world cup', 'fifa', 'goat', 'champions'],
    keywords: 'when the dream became immortal lionel messi world cup qatar 2022 argentina champions fifa goat football'
  },
  {
    file: '1551536.png',
    title: 'LIONEL MESSI | Cyan Shadow Profile',
    subtitle: 'Football Legends · Modernist Silhouette',
    category: 'Sports',
    collection: 'Football Legends',
    artist: 'Estadio Visuals',
    subject: 'High-contrast cyan and shadow side profile of Lionel Messi',
    badge: null,
    regularPrice: 799,
    salePrice: 599,
    rating: 4.8,
    reviewCount: 310,
    tags: ['sports', 'football', 'messi', 'lionel messi', 'cyan', 'silhouette', 'goat', 'athlete'],
    keywords: 'lionel messi cyan shadow profile goat barcelona argentina football athlete silhouette poster'
  },
  {
    file: '1553031.jpg',
    title: 'CRISTIANO RONALDO | Portugal #7 Crest',
    subtitle: 'Football Legends · Seleção das Quinas',
    category: 'Sports',
    collection: 'Football Legends',
    artist: 'CR7 Archival Studio',
    subject: 'Cristiano Ronaldo wearing Portugal captain armband against crimson crest',
    badge: 'POPULAR',
    regularPrice: 899,
    salePrice: 699,
    rating: 4.9,
    reviewCount: 780,
    tags: ['sports', 'football', 'ronaldo', 'cristiano ronaldo', 'cr7', 'portugal', 'champions', 'goat'],
    keywords: 'cristiano ronaldo cr7 portugal national team captain 7 selecao goat football legend jersey'
  },
  {
    file: '1553198.png',
    title: 'THE GREATEST PLAYER OF ALL TIME | Leo Messi',
    subtitle: 'Football Legends · Pitch Ball Mastery',
    category: 'Sports',
    collection: 'Football Legends',
    artist: 'Estadio Visuals',
    subject: 'Lionel Messi controlling ball on pitch with gold GOAT typography',
    badge: 'HOT',
    regularPrice: 899,
    salePrice: 699,
    rating: 5.0,
    reviewCount: 920,
    tags: ['sports', 'football', 'messi', 'lionel messi', 'goat', 'barcelona', 'argentina', 'athlete'],
    keywords: 'the greatest player of all time lionel messi goat football ball control pitch legend champions'
  },
  {
    file: '1553998.png',
    title: 'MESSI 10 | Argentina Sky Blue & Gold',
    subtitle: 'Football Legends · Albiceleste Celebration',
    category: 'Sports',
    collection: 'Football Legends',
    artist: 'Estadio Visuals',
    subject: 'Lionel Messi pointing two hands to the sky in Argentina stripes',
    badge: 'BESTSELLER',
    regularPrice: 899,
    salePrice: 699,
    rating: 5.0,
    reviewCount: 1450,
    tags: ['sports', 'football', 'messi', 'lionel messi', 'argentina', 'albiceleste', 'number 10', 'world cup'],
    keywords: 'messi 10 argentina albiceleste sky blue gold stars celebration grandmothers tribute football goat'
  },
  {
    file: '1554000.png',
    title: 'RED DEVIL | Cristiano Ronaldo Man United Classic',
    subtitle: 'Football Legends · Old Trafford 2008',
    category: 'Sports',
    collection: 'Football Legends',
    artist: 'CR7 Archival Studio',
    subject: 'Young Cristiano Ronaldo in red Vodafone AIG kit celebrating goal',
    badge: 'HOT',
    regularPrice: 899,
    salePrice: 699,
    rating: 4.9,
    reviewCount: 860,
    tags: ['sports', 'football', 'ronaldo', 'cristiano ronaldo', 'cr7', 'manchester united', 'premier league', 'old trafford'],
    keywords: 'cristiano ronaldo red devil manchester united old trafford premier league ballon dor 2008 cr7'
  },
  {
    file: '1554002.png',
    title: 'CRISTIANO RONALDO | Old Trafford Volley',
    subtitle: 'Football Legends · Mid-Air Strike',
    category: 'Sports',
    collection: 'Football Legends',
    artist: 'CR7 Archival Studio',
    subject: 'Cristiano Ronaldo airborne volley strike in Manchester United home kit',
    badge: null,
    regularPrice: 849,
    salePrice: 649,
    rating: 4.8,
    reviewCount: 420,
    tags: ['sports', 'football', 'ronaldo', 'cristiano ronaldo', 'cr7', 'manchester united', 'volley', 'premier league'],
    keywords: 'cristiano ronaldo mid-air volley strike old trafford manchester united cr7 premier league football'
  },
  {
    file: '1554004.png',
    title: 'LIONEL MESSI | Blaugrana Legend Blue Backdrop',
    subtitle: 'Football Legends · Camp Nou Glory',
    category: 'Sports',
    collection: 'Football Legends',
    artist: 'Estadio Visuals',
    subject: 'Lionel Messi in classic FC Barcelona kit against royal navy backdrop',
    badge: 'POPULAR',
    regularPrice: 849,
    salePrice: 649,
    rating: 4.9,
    reviewCount: 610,
    tags: ['sports', 'football', 'messi', 'lionel messi', 'barcelona', 'camp nou', 'blaugrana', 'champions league'],
    keywords: 'lionel messi barcelona blaugrana camp nou champions league la liga goat legend football'
  },
  {
    file: '1554013.png',
    title: 'GREATEST | Lionel Messi Camp Nou Red',
    subtitle: 'Football Legends · Vibrant Scarlet Edition',
    category: 'Sports',
    collection: 'Football Legends',
    artist: 'Estadio Visuals',
    subject: 'Lionel Messi celebrating facing Camp Nou crowd on scarlet red stage',
    badge: null,
    regularPrice: 849,
    salePrice: 649,
    rating: 4.8,
    reviewCount: 390,
    tags: ['sports', 'football', 'messi', 'lionel messi', 'barcelona', 'camp nou', 'goat', 'champions league'],
    keywords: 'lionel messi greatest camp nou crowd celebration scarlet red stage barcelona goat football'
  },
  {
    file: '1554016.png',
    title: 'JUST DO IT | Messi Kissing Barcelona Crest',
    subtitle: 'Football Legends · The Iconic Crest Kiss',
    category: 'Sports',
    collection: 'Football Legends',
    artist: 'Estadio Visuals',
    subject: 'Lionel Messi passionately kissing the FC Barcelona crest after Champions League goal',
    badge: 'BESTSELLER',
    regularPrice: 949,
    salePrice: 749,
    rating: 5.0,
    reviewCount: 1620,
    tags: ['sports', 'football', 'messi', 'lionel messi', 'barcelona', 'crest kiss', 'champions league', 'goat'],
    keywords: 'messi kissing crest barcelona just do it champions league final camp nou loyalty goat football'
  },
  {
    file: '1554018.png',
    title: 'CRISTIANO RONALDO | Pure Focus Match Profile',
    subtitle: 'Football Legends · Pre-Kick Ritual',
    category: 'Sports',
    collection: 'Football Legends',
    artist: 'CR7 Archival Studio',
    subject: 'Cristiano Ronaldo deep breathing stance before taking decisive free kick',
    badge: 'POPULAR',
    regularPrice: 849,
    salePrice: 649,
    rating: 4.9,
    reviewCount: 670,
    tags: ['sports', 'football', 'ronaldo', 'cristiano ronaldo', 'cr7', 'focus', 'free kick', 'athlete'],
    keywords: 'cristiano ronaldo pure focus match profile free kick stance breathing ritual cr7 athlete football'
  },
  {
    file: '1554020.png',
    title: 'CRISTIANO RONALDO | United Goal Smile',
    subtitle: 'Football Legends · Theater of Dreams Joy',
    category: 'Sports',
    collection: 'Football Legends',
    artist: 'CR7 Archival Studio',
    subject: 'Cristiano Ronaldo beaming with pure joy following last-minute winner',
    badge: null,
    regularPrice: 849,
    salePrice: 649,
    rating: 4.8,
    reviewCount: 450,
    tags: ['sports', 'football', 'ronaldo', 'cristiano ronaldo', 'cr7', 'manchester united', 'celebration', 'premier league'],
    keywords: 'cristiano ronaldo united goal smile old trafford celebration joy cr7 manchester united football'
  },
  {
    file: '1554022.png',
    title: 'CRISTIANO RONALDO | Free Kick Runup Red',
    subtitle: 'Football Legends · Knuckleball Stance',
    category: 'Sports',
    collection: 'Football Legends',
    artist: 'CR7 Archival Studio',
    subject: 'Iconic wide-legged stance of Cristiano Ronaldo before hitting knuckleball free kick',
    badge: 'TRENDING',
    regularPrice: 899,
    salePrice: 699,
    rating: 4.9,
    reviewCount: 710,
    tags: ['sports', 'football', 'ronaldo', 'cristiano ronaldo', 'cr7', 'knuckleball', 'free kick', 'premier league'],
    keywords: 'cristiano ronaldo free kick runup knuckleball stance wide stance power shot cr7 football legend'
  },
  {
    file: '1554024.png',
    title: 'STAY STRONG. BE BRAVE. | Ronaldo Header',
    subtitle: 'Football Legends · Aerial Mastery Print',
    category: 'Sports',
    collection: 'Football Legends',
    artist: 'CR7 Archival Studio',
    subject: 'Cristiano Ronaldo towering 2.93m airborne leap heading ball into top corner',
    badge: 'HOT',
    regularPrice: 899,
    salePrice: 699,
    rating: 5.0,
    reviewCount: 980,
    tags: ['sports', 'football', 'ronaldo', 'cristiano ronaldo', 'cr7', 'header', 'aerial', 'athlete', 'champions league'],
    keywords: 'stay strong be brave go beyond cristiano ronaldo header jump leap 2.93m airborne power cr7 football'
  },
  {
    file: '1555895.png',
    title: 'MANGA MESSI | Shonen Football Comic Art',
    subtitle: 'Football Legends · Anime & Manga Crossover',
    category: 'Sports',
    collection: 'Football Legends',
    artist: 'Tokyo Shonen Studio',
    subject: 'Lionel Messi illustrated in high-octane Japanese manga speedline panel',
    badge: 'POPULAR',
    regularPrice: 849,
    salePrice: 649,
    rating: 4.9,
    reviewCount: 650,
    tags: ['sports', 'football', 'messi', 'lionel messi', 'manga', 'anime', 'shonen', 'goat', 'blue lock'],
    keywords: 'manga messi shonen anime comic blue lock speedlines lionel messi japanese art crossover football'
  },
  {
    file: '1555898.png',
    title: 'THE SUMMIT | Messi Gazing at the World Cup',
    subtitle: 'Football Legends · Destiny Realized 2022',
    category: 'Sports',
    collection: 'Football Legends',
    artist: 'Estadio Visuals',
    subject: 'Lionel Messi walking past the golden FIFA World Cup trophy with serene gaze',
    badge: 'BESTSELLER',
    regularPrice: 949,
    salePrice: 749,
    rating: 5.0,
    reviewCount: 1780,
    tags: ['sports', 'football', 'messi', 'lionel messi', 'the summit', 'world cup', 'fifa', 'argentina', 'goat'],
    keywords: 'the summit lionel messi fifa world cup golden trophy destiny realized qatar 2022 goat argentina champions'
  },
  {
    file: '1556707.png',
    title: 'CRISTIANO RONALDO | Stadium Net Smile',
    subtitle: 'Football Legends · Goal Line Joy',
    category: 'Sports',
    collection: 'Football Legends',
    artist: 'CR7 Archival Studio',
    subject: 'Cristiano Ronaldo entangled in goal net smiling after thunderous finish',
    badge: null,
    regularPrice: 849,
    salePrice: 649,
    rating: 4.8,
    reviewCount: 390,
    tags: ['sports', 'football', 'ronaldo', 'cristiano ronaldo', 'cr7', 'goal net', 'celebration', 'athlete'],
    keywords: 'cristiano ronaldo stadium net smile goal celebration cr7 football soccer athlete joy'
  },
  {
    file: '1556717.png',
    title: 'CRISTIANO RONALDO | Training Ground Focus',
    subtitle: 'Football Legends · The Work in the Shadows',
    category: 'Sports',
    collection: 'Football Legends',
    artist: 'CR7 Archival Studio',
    subject: 'Cristiano Ronaldo sweat dripping in intense solo shooting drill',
    badge: null,
    regularPrice: 849,
    salePrice: 649,
    rating: 4.8,
    reviewCount: 340,
    tags: ['sports', 'football', 'ronaldo', 'cristiano ronaldo', 'cr7', 'training', 'focus', 'discipline', 'athlete'],
    keywords: 'cristiano ronaldo training focus workout sweat drill athlete discipline cr7 football'
  },
  {
    file: '1556721.png',
    title: 'CRISTIANO RONALDO | Vodafone United Roar',
    subtitle: 'Football Legends · The Young Prodigy Roar',
    category: 'Sports',
    collection: 'Football Legends',
    artist: 'CR7 Archival Studio',
    subject: 'Teenage Cristiano Ronaldo roaring with chest pumped in black and red Vodafone kit',
    badge: 'POPULAR',
    regularPrice: 899,
    salePrice: 699,
    rating: 4.9,
    reviewCount: 570,
    tags: ['sports', 'football', 'ronaldo', 'cristiano ronaldo', 'cr7', 'vodafone', 'manchester united', 'roar', 'premier league'],
    keywords: 'cristiano ronaldo vodafone manchester united roar young prodigy 2004 cr7 old trafford football'
  },
  {
    file: '1556725.png',
    title: 'CR7 POP ART | Retro Manchester United',
    subtitle: 'Football Legends · Warhol Screenprint Style',
    category: 'Sports',
    collection: 'Football Legends',
    artist: 'CR7 Archival Studio',
    subject: 'Four-quadrant vibrant pop art screenprint of Cristiano Ronaldo in red kit',
    badge: 'HOT',
    regularPrice: 849,
    salePrice: 649,
    rating: 4.9,
    reviewCount: 490,
    tags: ['sports', 'football', 'ronaldo', 'cristiano ronaldo', 'cr7', 'pop art', 'manchester united', 'retro'],
    keywords: 'cr7 pop art retro manchester united screenprint warhol vibrant colors cristiano ronaldo football poster'
  },
  {
    file: '1556894.png',
    title: 'GOAT WITH GOAT | Lionel Messi #19 Mascot',
    subtitle: 'Football Legends · Humorous Iconic Art',
    category: 'Sports',
    collection: 'Football Legends',
    artist: 'Estadio Visuals',
    subject: 'Young long-haired Lionel Messi in #19 jersey cradling cute live baby goat',
    badge: 'STAFF PICK',
    regularPrice: 899,
    salePrice: 699,
    rating: 5.0,
    reviewCount: 1350,
    tags: ['sports', 'football', 'messi', 'lionel messi', 'goat with goat', 'number 19', 'barcelona', 'goat'],
    keywords: 'goat with goat lionel messi live baby goat number 19 barcelona argentina paper mag tribute legend'
  },
  {
    file: '1557012.png',
    title: 'LEO IN PINK | Inter Miami Victory Fist',
    subtitle: 'Football Legends · Miami Sunset Flamingo',
    category: 'Sports',
    collection: 'Football Legends',
    artist: 'Estadio Visuals',
    subject: 'Lionel Messi in vibrant pink Inter Miami #10 kit raising fist to fireworks',
    badge: 'TRENDING',
    regularPrice: 899,
    salePrice: 699,
    rating: 4.9,
    reviewCount: 820,
    tags: ['sports', 'football', 'messi', 'lionel messi', 'inter miami', 'mls', 'pink', 'florida', 'goat'],
    keywords: 'leo in pink lionel messi inter miami mls victory fist chase stadium fireworks flamingo pink goat football'
  }
];

function generateSlug(title) {
  return title
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-+|-+$/g, '');
}

function verifyAssets() {
  console.log(`Checking ${posterCatalog.length} poster catalog entries against poster/opt/...`);
  let missing = 0;
  posterCatalog.forEach((p, idx) => {
    const baseName = path.parse(p.file).name;
    const webpPath = path.join(OPT_DIR, `${baseName}.webp`);
    const thumbPath = path.join(OPT_DIR, `${baseName}-thumb.webp`);
    if (!fs.existsSync(webpPath)) {
      console.error(`❌ Missing WebP for ${p.file}: ${webpPath}`);
      missing++;
    }
    if (!fs.existsSync(thumbPath)) {
      console.error(`❌ Missing Thumb for ${p.file}: ${thumbPath}`);
      missing++;
    }
  });

  if (missing === 0) {
    console.log(`✅ All ${posterCatalog.length} posters have verified WebP and Thumbnail files in poster/opt/!`);
  } else {
    console.error(`⚠️ Found ${missing} missing files!`);
    process.exit(1);
  }
}

verifyAssets();

module.exports = { posterCatalog, generateSlug };
