const fs = require('fs');

const newDriveItems = [
  {
    id: 152,
    slug: "virat-kohli-test-trophy",
    title: "VIRAT KOHLI | Domain Test Series Trophy Kiss",
    subtitle: "Cricket Legend · Border-Gavaskar Victory",
    category: "Sports",
    collection: "Cricket & Sports",
    artist: "Studio Pinboard",
    subject: "Virat Kohli kissing the Test trophy in white cricket whites",
    tags: ["sports", "cricket", "virat kohli", "kohli", "team india", "trophy"],
    keywords: "virat kohli cricket test series trophy king kohli team india sports",
    Size: "A4 (210 × 297 mm)",
    badge: "NEW",
    images: ["poster/opt/1562655.webp"],
    regularPrice: 99,
    salePrice: 60,
    rating: 4.9,
    reviewCount: 420,
    pieces: 1,
    material: "300 GSM Premium Matte Sheet",
    finish: "Smooth Matte Finish",
    frameIncluded: false,
    description: "Archival print of Virat Kohli celebrating Test series victory on 300 GSM museum-grade matte paper.",
    features: [
      "High contrast museum-grade print",
      "Printed on 300 GSM premium matte stock",
      "Rolled & packed flat in a rigid tube",
      "Ready to pin, tape, or frame"
    ]
  },
  {
    id: 153,
    slug: "amazing-spiderman-memory-collage",
    title: "THE AMAZING SPIDER-MAN 2 | Peter & Gwen Memory Collage",
    subtitle: "Marvel Cinema · Andrew Garfield & Emma Stone",
    category: "Movies",
    collection: "Superhero & Cinema",
    artist: "Studio Pinboard",
    subject: "The Amazing Spider-Man 2 romantic and dramatic scene collage",
    tags: ["movies", "marvel", "spider-man", "spiderman", "peter parker", "gwen stacy", "andrew garfield"],
    keywords: "the amazing spiderman 2 peter parker gwen stacy andrew garfield emma stone marvel movie poster",
    Size: "A4 (210 × 297 mm)",
    badge: "NEW",
    images: ["poster/opt/1562656.webp"],
    regularPrice: 99,
    salePrice: 60,
    rating: 4.9,
    reviewCount: 512,
    pieces: 1,
    material: "300 GSM Premium Matte Sheet",
    finish: "Smooth Matte Finish",
    frameIncluded: false,
    description: "Vibrant movie artwork print of Andrew Garfield and Emma Stone in The Amazing Spider-Man 2.",
    features: [
      "Vivid cinematic color print",
      "Printed on 300 GSM museum matte paper",
      "Rolled & packed flat in a rigid tube",
      "Ready to pin, tape, or frame"
    ]
  },
  {
    id: 154,
    slug: "captain-america-vs-captain-america",
    title: "CAPTAIN AMERICA VS CAPTAIN AMERICA | Stark Tower Battle",
    subtitle: "Avengers Endgame · Shield Clash",
    category: "Movies",
    collection: "Superhero & Cinema",
    artist: "Studio Pinboard",
    subject: "Captain America fighting past Captain America at Stark Tower in Endgame",
    tags: ["movies", "marvel", "avengers", "endgame", "captain america", "steve rogers", "shield"],
    keywords: "captain america vs captain america stark tower avengers endgame shield clash marvel movies",
    Size: "A4 (210 × 297 mm)",
    badge: "NEW",
    images: ["poster/opt/1562657.webp"],
    regularPrice: 99,
    salePrice: 60,
    rating: 4.8,
    reviewCount: 388,
    pieces: 1,
    material: "300 GSM Premium Matte Sheet",
    finish: "Smooth Matte Finish",
    frameIncluded: false,
    description: "Archival cinematic print of the legendary Captain America vs Captain America battle scene.",
    features: [
      "High detail architectural glass perspective",
      "Printed on 300 GSM premium matte stock",
      "Rolled & packed flat in a rigid tube",
      "Ready to pin, tape, or frame"
    ]
  },
  {
    id: 155,
    slug: "worthy-captain-america-thanos",
    title: "WORTHY CAPTAIN AMERICA | Lightning Strike on Thanos",
    subtitle: "Avengers Endgame · Mjolnir & Thunder",
    category: "Movies",
    collection: "Superhero & Cinema",
    artist: "Studio Pinboard",
    subject: "Worthy Captain America wielding Mjolnir with lightning against Thanos",
    tags: ["movies", "marvel", "avengers", "endgame", "captain america", "mjolnir", "thanos", "thor"],
    keywords: "worthy captain america mjolnir lightning thanos battle avengers endgame marvel movies",
    Size: "A4 (210 × 297 mm)",
    badge: "NEW",
    images: ["poster/opt/1562658.webp"],
    regularPrice: 99,
    salePrice: 60,
    rating: 4.95,
    reviewCount: 740,
    pieces: 1,
    material: "300 GSM Premium Matte Sheet",
    finish: "Smooth Matte Finish",
    frameIncluded: false,
    description: "Epic thunderous print of Captain America lifting Thor's hammer in Endgame.",
    features: [
      "Deep electric blue lightning tone",
      "Printed on 300 GSM premium matte paper",
      "Rolled & packed flat in a rigid tube",
      "Ready to pin, tape, or frame"
    ]
  },
  {
    id: 156,
    slug: "king-kohli-rcb-crown",
    title: "KING KOHLI | Royal Challengers Bengaluru Crown",
    subtitle: "Cricket Royalty · RCB Gold Lion",
    category: "Sports",
    collection: "Cricket & Sports",
    artist: "Studio Pinboard",
    subject: "Virat Kohli wearing a golden crown with RCB smoke typography and lion cape",
    tags: ["sports", "cricket", "virat kohli", "king kohli", "rcb", "royal challengers", "ipl"],
    keywords: "king kohli rcb royal challengers bengaluru crown lion virat kohli cricket sports",
    Size: "A4 (210 × 297 mm)",
    badge: "NEW",
    images: ["poster/opt/1562659.webp"],
    regularPrice: 99,
    salePrice: 60,
    rating: 4.9,
    reviewCount: 680,
    pieces: 1,
    material: "300 GSM Premium Matte Sheet",
    finish: "Smooth Matte Finish",
    frameIncluded: false,
    description: "Majestic portrait of King Kohli crowned with the golden RCB lion crest.",
    features: [
      "Rich golden smoke effect",
      "Printed on 300 GSM museum matte paper",
      "Rolled & packed flat in a rigid tube",
      "Ready to pin, tape, or frame"
    ]
  },
  {
    id: 157,
    slug: "virat-kohli-18-rcb-walk",
    title: "VIRAT KOHLI #18 | Walking into the Arena",
    subtitle: "IPL Legend · Tamil Karuppa Edition",
    category: "Sports",
    collection: "Cricket & Sports",
    artist: "Studio Pinboard",
    subject: "Virat Kohli #18 carrying bat over shoulder walking onto stadium grass",
    tags: ["sports", "cricket", "virat kohli", "rcb", "18", "kohli", "ipl", "stadium"],
    keywords: "virat kohli 18 rcb cricket walking onto pitch stadium bat sports",
    Size: "A4 (210 × 297 mm)",
    badge: "NEW",
    images: ["poster/opt/1562660.webp"],
    regularPrice: 99,
    salePrice: 60,
    rating: 4.88,
    reviewCount: 490,
    pieces: 1,
    material: "300 GSM Premium Matte Sheet",
    finish: "Smooth Matte Finish",
    frameIncluded: false,
    description: "Back view artwork of Virat Kohli in jersey #18 stepping into the stadium.",
    features: [
      "Stadium turf color grading",
      "Printed on 300 GSM premium matte stock",
      "Rolled & packed flat in a rigid tube",
      "Ready to pin, tape, or frame"
    ]
  },
  {
    id: 158,
    slug: "ab-de-villiers-south-africa-legend",
    title: "AB DE VILLIERS | Mr. 360 South Africa Legend",
    subtitle: "Cricket Icon · Proteas Green & Gold",
    category: "Sports",
    collection: "Cricket & Sports",
    artist: "Studio Pinboard",
    subject: "AB de Villiers in South Africa kit in deep contemplation",
    tags: ["sports", "cricket", "ab de villiers", "abd", "360", "south africa", "proteas"],
    keywords: "ab de villiers abd mr 360 south africa cricket proteas sports legend",
    Size: "A4 (210 × 297 mm)",
    badge: "NEW",
    images: ["poster/opt/1562661.webp"],
    regularPrice: 99,
    salePrice: 60,
    rating: 4.9,
    reviewCount: 360,
    pieces: 1,
    material: "300 GSM Premium Matte Sheet",
    finish: "Smooth Matte Finish",
    frameIncluded: false,
    description: "Classic portrait of AB de Villiers in his iconic South Africa cricket whites and green.",
    features: [
      "Proteas green color fidelity",
      "Printed on 300 GSM museum matte paper",
      "Rolled & packed flat in a rigid tube",
      "Ready to pin, tape, or frame"
    ]
  },
  {
    id: 159,
    slug: "virat-kohli-rcb-studio-badge",
    title: "VIRAT KOHLI | Red Studio Badge Focus",
    subtitle: "Puma & RCB · Studio Lighting",
    category: "Sports",
    collection: "Cricket & Sports",
    artist: "Studio Pinboard",
    subject: "Virat Kohli seated in red studio room pointing to RCB badge",
    tags: ["sports", "cricket", "virat kohli", "rcb", "puma", "studio", "fashion"],
    keywords: "virat kohli studio badge rcb red room cricket sports puma",
    Size: "A4 (210 × 297 mm)",
    badge: "NEW",
    images: ["poster/opt/1562662.webp"],
    regularPrice: 99,
    salePrice: 60,
    rating: 4.85,
    reviewCount: 310,
    pieces: 1,
    material: "300 GSM Premium Matte Sheet",
    finish: "Smooth Matte Finish",
    frameIncluded: false,
    description: "Editorial portrait print of Virat Kohli in the RCB red studio lounge.",
    features: [
      "Warm red studio background",
      "Printed on 300 GSM premium matte stock",
      "Rolled & packed flat in a rigid tube",
      "Ready to pin, tape, or frame"
    ]
  },
  {
    id: 160,
    slug: "the-notorious-conor-mcgregor",
    title: "THE NOTORIOUS | Conor McGregor UFC Champion Collage",
    subtitle: "Combat Sports · UFC Double Champ",
    category: "Sports",
    collection: "Combat & Fitness",
    artist: "Studio Pinboard",
    subject: "Conor McGregor monochrome ripped paper collage with belts",
    tags: ["sports", "ufc", "conor mcgregor", "notorious", "fighting", "mma", "champ"],
    keywords: "the notorious conor mcgregor ufc mma champion belt combat sports",
    Size: "A4 (210 × 297 mm)",
    badge: "NEW",
    images: ["poster/opt/1562663.webp"],
    regularPrice: 99,
    salePrice: 60,
    rating: 4.92,
    reviewCount: 570,
    pieces: 1,
    material: "300 GSM Premium Matte Sheet",
    finish: "Smooth Matte Finish",
    frameIncluded: false,
    description: "Edgy monochrome collage poster of Conor McGregor's championship moments.",
    features: [
      "Monochrome high contrast graphic design",
      "Printed on 300 GSM museum matte paper",
      "Rolled & packed flat in a rigid tube",
      "Ready to pin, tape, or frame"
    ]
  },
  {
    id: 161,
    slug: "peter-gwen-golden-sunset-romance",
    title: "PETER & GWEN | Golden Sunset Romance",
    subtitle: "Marvel Cinema · The Amazing Spider-Man",
    category: "Movies",
    collection: "Superhero & Cinema",
    artist: "Studio Pinboard",
    subject: "Peter Parker and Gwen Stacy embracing under golden sunset with web-slinging Spidey",
    tags: ["movies", "marvel", "spider-man", "spiderman", "peter parker", "gwen stacy"],
    keywords: "peter and gwen golden sunset romance amazing spiderman marvel movies",
    Size: "A4 (210 × 297 mm)",
    badge: "NEW",
    images: ["poster/opt/1562664.webp"],
    regularPrice: 99,
    salePrice: 60,
    rating: 4.88,
    reviewCount: 410,
    pieces: 1,
    material: "300 GSM Premium Matte Sheet",
    finish: "Smooth Matte Finish",
    frameIncluded: false,
    description: "Warm golden glow artwork of Peter Parker & Gwen Stacy's romance.",
    features: [
      "Golden hour cinematic tone",
      "Printed on 300 GSM premium matte stock",
      "Rolled & packed flat in a rigid tube",
      "Ready to pin, tape, or frame"
    ]
  },
  {
    id: 162,
    slug: "dodge-challenger-srt-demon",
    title: "DODGE CHALLENGER SRT DEMON | Red Stripe Muscle",
    subtitle: "American Muscle · SRT Demon 840 HP",
    category: "Cars",
    collection: "Supercars & Automotive",
    artist: "Studio Pinboard",
    subject: "Dark Dodge Challenger SRT Demon with red stripes and bold DODGE typography",
    tags: ["cars", "dodge", "challenger", "srt demon", "american muscle", "automotive", "supercars"],
    keywords: "dodge challenger srt demon red stripe american muscle car poster",
    Size: "A4 (210 × 297 mm)",
    badge: "NEW",
    images: ["poster/opt/1562810.webp"],
    regularPrice: 99,
    salePrice: 60,
    rating: 4.9,
    reviewCount: 630,
    pieces: 1,
    material: "300 GSM Premium Matte Sheet",
    finish: "Smooth Matte Finish",
    frameIncluded: false,
    description: "Bold American muscle poster of the Dodge Challenger SRT Demon.",
    features: [
      "Aggressive red slab typography",
      "Printed on 300 GSM museum matte paper",
      "Rolled & packed flat in a rigid tube",
      "Ready to pin, tape, or frame"
    ]
  },
  {
    id: 163,
    slug: "toyota-supra-mk4-burnout-smoke",
    title: "TOYOTA SUPRA MK4 | Red Typography Burnout",
    subtitle: "JDM Legend · 2JZ-GTE Turbo",
    category: "Cars",
    collection: "JDM & Speed",
    artist: "Studio Pinboard",
    subject: "Black Toyota Supra MK4 doing a burnout in heavy smoke with red SUPRA text",
    tags: ["cars", "jdm", "toyota", "supra", "mk4", "2jz", "burnout", "automotive"],
    keywords: "toyota supra mk4 jdm 2jz burnout red typography cars poster",
    Size: "A4 (210 × 297 mm)",
    badge: "NEW",
    images: ["poster/opt/1562818.webp"],
    regularPrice: 99,
    salePrice: 60,
    rating: 4.95,
    reviewCount: 820,
    pieces: 1,
    material: "300 GSM Premium Matte Sheet",
    finish: "Smooth Matte Finish",
    frameIncluded: false,
    description: "Iconic JDM poster of the black Toyota Supra MK4 emerging from burnout smoke.",
    features: [
      "Volumetric smoke and red halo lights",
      "Printed on 300 GSM premium matte paper",
      "Rolled & packed flat in a rigid tube",
      "Ready to pin, tape, or frame"
    ]
  },
  {
    id: 164,
    slug: "porsche-911-gt3-rs-black-forest-specs",
    title: "PORSCHE 911 GT3 RS | Black Forest Performance Specs",
    subtitle: "German Engineering · 510 HP Specs",
    category: "Cars",
    collection: "Supercars & Automotive",
    artist: "Studio Pinboard",
    subject: "Porsche 911 GT3 RS on wet forest road with performance specification sheet",
    tags: ["cars", "porsche", "911", "gt3 rs", "supercars", "german", "automotive"],
    keywords: "porsche 911 gt3 rs black forest Germany 510 hp specs supercar poster",
    Size: "A4 (210 × 297 mm)",
    badge: "NEW",
    images: ["poster/opt/1562819.webp"],
    regularPrice: 99,
    salePrice: 60,
    rating: 4.92,
    reviewCount: 690,
    pieces: 1,
    material: "300 GSM Premium Matte Sheet",
    finish: "Smooth Matte Finish",
    frameIncluded: false,
    description: "Detailed automotive poster featuring the Porsche 911 GT3 RS with technical specs.",
    features: [
      "Clear technical spec layout",
      "Printed on 300 GSM museum matte stock",
      "Rolled & packed flat in a rigid tube",
      "Ready to pin, tape, or frame"
    ]
  },
  {
    id: 165,
    slug: "ford-mustang-50l-v8-freedom",
    title: "FORD MUSTANG 5.0L V8 | Racing Stripe Freedom",
    subtitle: "American Muscle · 486 HP V8",
    category: "Cars",
    collection: "Supercars & Automotive",
    artist: "Studio Pinboard",
    subject: "Black Ford Mustang GT 5.0L V8 with white & red racing stripe on wet tarmac",
    tags: ["cars", "ford", "mustang", "v8", "american muscle", "automotive", "supercars"],
    keywords: "ford mustang gt 5.0 v8 racing stripe american muscle car poster",
    Size: "A4 (210 × 297 mm)",
    badge: "NEW",
    images: ["poster/opt/1562820.webp"],
    regularPrice: 99,
    salePrice: 60,
    rating: 4.89,
    reviewCount: 530,
    pieces: 1,
    material: "300 GSM Premium Matte Sheet",
    finish: "Smooth Matte Finish",
    frameIncluded: false,
    description: "Sleek dark-mode poster of the Ford Mustang 5.0L V8 GT.",
    features: [
      "Wet tarmac reflection",
      "Printed on 300 GSM premium matte stock",
      "Rolled & packed flat in a rigid tube",
      "Ready to pin, tape, or frame"
    ]
  },
  {
    id: 166,
    slug: "not-everyone-gets-the-vision-cr7",
    title: "NOT EVERYONE GETS THE VISION | Young CR7 Manchester United",
    subtitle: "Football Legend · CR7 Quote",
    category: "Sports",
    collection: "Football Legends",
    artist: "Studio Pinboard",
    subject: "Young Cristiano Ronaldo in Manchester United blue kit with vision quote",
    tags: ["sports", "football", "cristiano ronaldo", "cr7", "manchester united", "vision", "quote"],
    keywords: "not everyone gets the vision cristiano ronaldo cr7 manchester united football sports poster",
    Size: "A4 (210 × 297 mm)",
    badge: "NEW",
    images: ["poster/opt/1562826.webp"],
    regularPrice: 99,
    salePrice: 60,
    rating: 4.93,
    reviewCount: 710,
    pieces: 1,
    material: "300 GSM Premium Matte Sheet",
    finish: "Smooth Matte Finish",
    frameIncluded: false,
    description: "Motivational football poster of young Cristiano Ronaldo at Old Trafford.",
    features: [
      "High typography contrast",
      "Printed on 300 GSM museum matte paper",
      "Rolled & packed flat in a rigid tube",
      "Ready to pin, tape, or frame"
    ]
  },
  {
    id: 167,
    slug: "we-want-to-show-our-dreams-cr7",
    title: "WE WANT TO SHOW OUR DREAMS | CR7 Old Trafford Roar",
    subtitle: "Football Legend · Red #7 Roar",
    category: "Sports",
    collection: "Football Legends",
    artist: "Studio Pinboard",
    subject: "Cristiano Ronaldo celebrating fiercely in red Manchester United kit",
    tags: ["sports", "football", "cristiano ronaldo", "cr7", "manchester united", "dreams"],
    keywords: "we dont want to tell our dreams we want to show them ronaldo cr7 football poster",
    Size: "A4 (210 × 297 mm)",
    badge: "NEW",
    images: ["poster/opt/1562840.webp"],
    regularPrice: 99,
    salePrice: 60,
    rating: 4.96,
    reviewCount: 890,
    pieces: 1,
    material: "300 GSM Premium Matte Sheet",
    finish: "Smooth Matte Finish",
    frameIncluded: false,
    description: "Fierce passion poster of Cristiano Ronaldo screaming in Manchester United red.",
    features: [
      "Vivid red and black contrast",
      "Printed on 300 GSM premium matte stock",
      "Rolled & packed flat in a rigid tube",
      "Ready to pin, tape, or frame"
    ]
  },
  {
    id: 168,
    slug: "dont-stop-when-youre-tired-neymar",
    title: "DON'T STOP WHEN YOU'RE TIRED | Neymar Jr #10 Brazil",
    subtitle: "Football Legend · Brazil #10",
    category: "Sports",
    collection: "Football Legends",
    artist: "Studio Pinboard",
    subject: "Neymar Jr #10 in yellow Brazil kit walking into darkness with quote",
    tags: ["sports", "football", "neymar", "neymar jr", "brazil", "10", "motivation"],
    keywords: "dont stop when youre tired stop when youre done neymar jr brazil football poster",
    Size: "A4 (210 × 297 mm)",
    badge: "NEW",
    images: ["poster/opt/1562841.webp"],
    regularPrice: 99,
    salePrice: 60,
    rating: 4.91,
    reviewCount: 640,
    pieces: 1,
    material: "300 GSM Premium Matte Sheet",
    finish: "Smooth Matte Finish",
    frameIncluded: false,
    description: "Inspirational sports poster of Neymar Jr #10 walking under spotlight.",
    features: [
      "Spotlight focus on yellow Brazil jersey",
      "Printed on 300 GSM museum matte paper",
      "Rolled & packed flat in a rigid tube",
      "Ready to pin, tape, or frame"
    ]
  },
  {
    id: 169,
    slug: "bmw-m8-gran-coupe-alpine",
    title: "BMW M8 GRAN COUPE | Alpine M-Performance",
    subtitle: "German Supercar · Gran Coupe",
    category: "Cars",
    collection: "Supercars & Automotive",
    artist: "Studio Pinboard",
    subject: "Black BMW M8 Gran Coupe against snowy mountain peak with M stripes",
    tags: ["cars", "bmw", "m8", "gran coupe", "m performance", "supercars", "automotive"],
    keywords: "bmw m8 gran coupe alpine m performance german supercar poster",
    Size: "A4 (210 × 297 mm)",
    badge: "NEW",
    images: ["poster/opt/1562842.webp"],
    regularPrice: 99,
    salePrice: 60,
    rating: 4.94,
    reviewCount: 780,
    pieces: 1,
    material: "300 GSM Premium Matte Sheet",
    finish: "Smooth Matte Finish",
    frameIncluded: false,
    description: "Stunning alpine supercar poster of the BMW M8 Gran Coupe.",
    features: [
      "M-performance tricolor stripe",
      "Printed on 300 GSM premium matte stock",
      "Rolled & packed flat in a rigid tube",
      "Ready to pin, tape, or frame"
    ]
  }
];

let code = fs.readFileSync('js/products-data.js', 'utf8');

const targetStr = '// ---------- SEPARATE COLLECTION PROFILE DATASET ----------';
if (!code.includes(targetStr)) {
  console.error('Target string not found!');
  process.exit(1);
}

const formattedNewItems = '  ,\n' + newDriveItems.map(item => '  ' + JSON.stringify(item, null, 2).replace(/\n/g, '\n  ')).join(',\n') + '\n];\n\n';

const updatedCode = code.replace('];\n\n' + targetStr, formattedNewItems + targetStr);

fs.writeFileSync('js/products-data.js', updatedCode, 'utf8');
console.log(`Successfully integrated ${newDriveItems.length} new Drive poster products into PINBOARD_PRODUCTS catalog.`);
